### ISSUE TITLE
The cd command autocompletes local directories even on a remote ssh connection

### ISSUE THREAD

**Issue by william-matz** [withfig/autocomplete#1]
When I ssh into another machine and use the cd command, it autocompletes directories from my local machine, not the remote

**Comment by falky97** [comment]
Got it. 

For the moment, we will turn off autocomplete when you're in a remote machine. But we are exploring ways to make it work. 

SSH is encrypted, so understandably, tapping into a connection is hard!

Will leave the issue open for the moment and use this as the space to discuss our progress on making it work.

**Comment by dipakparmar** [comment]
@falky97 could be possible to do with [ssh tunnelling](https://www.ssh.com/ssh/tunneling/example#:~:text=Local%20Forwarding)? 🤔

**Comment by falky97** [comment]
@dipakparmar Agree. Pseudo terminals also a possibility. Ideally something that fits within the running process. Ideas welcome. This stack exchange post I did may shed some more light. https://unix.stackexchange.com/questions/614052/get-working-directory-inside-ssh-client-process-from-outside-process. Answer was a bit cryptic 😬

**Comment by falky97** [comment]
Some more things to investigate:
* https://mosh.org/#techinfo & https://mosh.org/mosh-paper.pdf
* emacs tramp 
* eshell

**Comment by falky97** [comment]
v1.0.27 (just pushed) has fixed this.

1. When in SSH, we will now no longer show any suggestions for things that require a background process. e.g. file/folders, git remotes, heroku apps etc. We will still show subcommands normally.
2. When in a process that's not SSH, Bash, Zsh, or Fish, Fig will not deliver suggestions (e.g. if you're in a python repl)

Genius work from @mattschrage to get this working.
