### ISSUE TITLE
Docksal's `fin` client

### ISSUE THREAD

**Issue by mattbloomfield** [withfig/autocomplete#101]
### CLI Tool
What CLI tool is missing autocompletion in Fig?

`fin` (Docksal's CLI)

### Useful Links
Please add some links to the docs of that tool or the `--help`text

https://docs.docksal.io/fin/fin-help/

### Top Workflows
What are the most used commands or workflows in that CLI tool (for you)?

fin restart
fin project reset cli
fin start
fin stop
fin <custom_command> (found in `.docksal/commands/*`

**Comment by mattschrage** [comment]
@mattbloomfield is this blocked by #106 - should we try to build out the skeleton for the CLI or wait until we can dynamically generate subcommands?

**Comment by SeparateRecords** [comment]
Done!
