### ISSUE TITLE
pip3 integration

### ISSUE THREAD

**Issue by Lidor-Abo** [withfig/autocomplete#1017]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Hey, why only pip autocomplete working?
i using pip3 and from the time that i created alias to pip3 in .zshrc file auto complete not working for me?
Maybe you added support for pip3 in the future?

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.2.1 21D62|1.0.55|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.55 (B383) [ABC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/lidor/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/lidor/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (8580) - /dev/ttys010
Current working directory: /Users/lidor
Current window identifier: 4867/% (com.googlecode.iterm2)
Path: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/lidor/.fig/bin
Fig environment variables:
  - TERM_SESSION_ID=w0t0p0:927E3E3C-DB94-42D8-8566-F1279A39BC8A
  - FIG_INTEGRATION_VERSION=6
  - FIG_TERM=1
  - FIG_TERM_VERSION=4.0.10
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
MacOS Version: 12.2.1 21D62
Hardware:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,1
  - Chip: Apple M1 Pro
  - Cores: 10 (8 performance and 2 efficiency)
  - Memory: 32 GB</pre>
</p>
</details>

**Comment by JodyZ0203** [comment]
[754ea08](https://github.com/withfig/autocomplete/commit/754ea08eb2da6ef29e7cb7d108a9a55ab357e98f)
This can be closed as its done in this commit.
