### ISSUE TITLE
[sed] request for spec

### ISSUE THREAD

**Issue by classicrob** [withfig/autocomplete#102]
### CLI Tool
sed

### Useful Links
https://www.gnu.org/software/sed/manual/sed.html

### Top Workflows
What are the most used commands or workflows in that CLI tool (for you)?

Generally just text management and formatting! I use Obsidian for my notes, so all of my work is in text files and I would love an easier way to write commands for sed!

**Comment by Nutlope** [comment]
Would love to work on this as my first issue. Thanks for adding the tag @cstrnt. Do you recommend I just look up the top most common workflows with sed and include them with the PR?

**Comment by QuiiBz** [comment]
Merged in #335, thanks everyone!

**Comment by classicrob** [comment]
Thank you!
