### ISSUE TITLE
[ripgrep] and [grep] request for specs

### ISSUE THREAD

**Issue by classicrob** [withfig/autocomplete#103]
### CLI Tool
What CLI tool is missing autocompletion in Fig?

ripgrep and grep

### Useful Links
Please add some links to the docs of that tool or the `--help`text

https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md

https://www.gnu.org/software/grep/manual/grep.html

### Top Workflows
What are the most used commands or workflows in that CLI tool (for you)?

Searching text within directories and providing the appropriate amount of context before and after. Piping that into other outputs.

**Comment by M-ZubairAhmed** [comment]
Hey how can i contribute to this?

**Comment by cstrnt** [comment]
Hey there @classicrob,

`grep` is already implemented in a very basic manner, but `ripgrep` isn't yet.
Do you know how those tools work? We would really appreciate if you could help us :)

**Comment by classicrob** [comment]
@cstrnt , how can I help?

**Comment by cstrnt** [comment]
@classicrob Either by creating a new completion spec for `ripgrep` yourself or having a look at the current `grep` spec and checking if that one is correct 😊

**Comment by QuiiBz** [comment]
`ripgrep` has been merged into #332!

**Comment by classicrob** [comment]
Thank you!
