### ISSUE TITLE
[gh] `gh repo clone` generator fails when user in >100 repos

### ISSUE THREAD

**Issue by SeparateRecords** [withfig/autocomplete#1039]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [ ] I would like to work on this.

### What CLI tool does this relate to?

gh

### Which statement makes the most sense?

There is a bug with this completion spec

### Issue Details

When a user is in more than 100 repos, `--paginate` causes it to output multiple JSON objects (but _not_ as an array) so it fails parsing as JSON

```jsonc
{
  // Page 1
}
{
  // Page 2
}
```

cc @ShawnCockburn

**Comment by ShawnCockburn** [comment]
fixed in https://github.com/withfig/autocomplete/pull/1047#issue-1178746036
