### ISSUE TITLE
[Bug] kubectl --dry-run=client shortcut - misspelled value

### ISSUE THREAD

**Issue by shakir185** [withfig/autocomplete#1058]
### Description:
The `kubectl`, `--dry-run=client` shortcut prints the "client" part with an uppercase "C" which makes the `kubectl` command to fail.
![](https://i.imgur.com/yWilp47.png)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.2.1|Version 1.0.56 (B416)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.56 (B416) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/xxxxx/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: /Users/xxxxx/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/xxxxx/.local/bin:/Users/xxxxx/.fig/bin:/Users/xxxxx/.local/bin:/Users/xxxxx/.local/bin:/Users/xxxxx/Library/Python/3.8/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/xxxxx/.local/bin:/Users/xxxxx/.fig/bin:/Users/xxxxx/.local/bin:/Users/xxxxx/.local/bin:/usr/local/mysql/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by fedeci** [comment]
Fixed in a recently merged PR!
