### ISSUE TITLE
[kubectl]suggestions supplement

### ISSUE THREAD

**Issue by jzhupup** [withfig/autocomplete#1059]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [X] I would like to work on this.

### What CLI tool does this relate to?

kubectl

### Which statement makes the most sense?

This completion spec isn't complete

### Issue Details

**Address：**
https://github.com/withfig/autocomplete/blob/49d2fd711e30eb478987c97c622a5c19f9987775/src/kubectl.ts#L1327-L1334
https://github.com/withfig/autocomplete/blob/49d2fd711e30eb478987c97c622a5c19f9987775/src/kubectl.ts#L610-L619

I think we should have more commonly used verbs is suggestions，such as  "*", "get", "delete", "list", "create", "update", "patch", "watch"，you can ref the check in kubectl validResourceVerbs，https://github.com/kubernetes/kubectl/blob/fdbcc2710435e59cee996dccd6d219b4ed98fff3/pkg/cmd/create/create_role.go#L60

**Comment by mschrage** [comment]
It would be great to support more of these! Looking forward to your PR @jzhupup 🤞

Let me know if you need any help with the completion spec format!
