### ISSUE TITLE
Dynamically generate subcommands (with their own nested subcommands and flags)

### ISSUE THREAD

**Issue by mattschrage** [withfig/autocomplete#106]
Several CLI tools enable users to add their own commands (`rails`, `laravel`, `fin`).

Currently, Fig's completion spec standard supports dynamically listing suggestions for arguments, but not generating nested structures (like subcommands and options).

**Request:** Can we add the ability to add nested suggestions (with their own subcommands and flags) to the completion spec at runtime.

**Comment by falky97** [comment]
This is now possible. Used the `generateSpec` prop of a subcommand object: https://withfig.com/docs/autocomplete/api
