### ISSUE TITLE
Support for file redirection

### ISSUE THREAD

**Issue by mschrage** [withfig/autocomplete#107]
### Description
Fig does not present `filepath` suggestions when using file redirects. 

### Steps to reproduce
After typing `pbpaste > ` Fig should pop up suggestions for filespaths. (Similar behavior should exists for `2>`, `<`, `>>`, etc)

**Comment by falky97** [comment]
Will need to update our bash parser. 

This will be doable: >, >>, <, <<, &> et
This will be a pain in the arse: 2>

**Comment by SeparateRecords** [comment]
Works fine now when there's a space after the redirect, which is arguably the correct behavior!
