### ISSUE TITLE
conda

### ISSUE THREAD

**Issue by acgetchell** [withfig/autocomplete#1083]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [ ] I would like to work on this.

### What CLI tool does this relate to?

conda

### Which statement makes the most sense?

There is a bug with this completion spec

### Issue Details

[![asciicast](https://asciinema.org/a/7mJSZLkM3Mi5ZyGH00FrTamrw.svg)](https://asciinema.org/a/7mJSZLkM3Mi5ZyGH00FrTamrw)

**Comment by fedeci** [comment]
Do other specs work correctly?

**Comment by acgetchell** [comment]
`conda remove` is similarly broken.

**Comment by fedeci** [comment]
What about specs for entirely different commands? e.g. `npm` or `cd`

**Comment by acgetchell** [comment]
`cd` and `brew` work fine, I've so far only noticed issues with `conda`.
