### ISSUE TITLE
[webpack] missing spec

### ISSUE THREAD

**Issue by neoncitylights** [withfig/autocomplete#1084]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [X] I would like to work on this.

### What CLI tool does this relate to?

https://github.com/webpack/webpack-cli

### Which statement makes the most sense?

This completion spec does not exist

### Issue Details

 - Main/most often used options/subcommands are documented on webpack's [official website](https://webpack.js.org/api/cli/)
 - All options/subcommands are documented under the [`OPTIONS.md`](https://github.com/webpack/webpack-cli/blob/master/OPTIONS.md) file of the `webpack/webpack-cli`, which also shows when running `webpack --help=verbose`

----
In total, the webpack CLI provides almost *1,000* options! So, I wrote a script to parse the help manual at`OPTIONS.md` to help generate some JSON for scaffolding (since I didn't want to manually convert it all by hand): https://gist.github.com/neoncitylights/22cc1e97d19e11c0eca3980ec31993ec

There is also a [TypeScript playground](https://tsplay.dev/NVa2Zw) available if you'd like to run it!

I also just recently realized that Fig's type definitions are also public (!), so I'm currently working on to migrate the types and do a slight refactor, then submit for PR when ready.

If it would be easier to start with for PR reviewing, I can also submit a PR with just the main options documented on webpack's official website, and expand from there in a followup PR.

**Comment by fedeci** [comment]
Thanks @neoncitylights!
