### ISSUE TITLE
Introduce an complete-on-demand option in addition to autocomplete

### ISSUE THREAD

**Issue by mmerdes** [withfig/autocomplete#109]
### Completion Spec

Fig itself

### Description

whenever I use a shell command supported by fig (e.g. git) autocomplete strikes immediately sometimes interrupting my thought process.

### Steps to reproduce

core behavior 

### Expected result

An option to summon the completion suggestions on demand would be great
(Like hitting the TAB key in a standard shell)

### Actual result

autocomplete always strikes

**Comment by falky97** [comment]
This is done in v1.0.41.

To turn on:
```
fig settings autocomplete.onlyShowOnTab true
```

And to turn off
```
fig settings autocomplete.onlyShowOnTab false
```
