### ISSUE TITLE
The commands `npm run dev`, `npm copy` and `npm copy:all` don't work.

### ISSUE THREAD

**Issue by cstrnt** [withfig/autocomplete#110]
### Description

The commands `npm run dev`, `npm copy` and `npm copy:all` don't work.

### Steps to reproduce

- Run either of those commands with Node version > 15 and npm version > 7

### Expected result

The commands just work fine

### Actual result

They don't work

### System Information
 
*Node Version*: `v15.3.0`
*NPM Version*: `7.0.14`

### Potential Solution

Use `$(pwd)` instead of `$INIT_CWD`

**Comment by falky97** [comment]
Fixed in https://github.com/withfig/autocomplete/pull/113
