### ISSUE TITLE
Add a setting to hide fig when the next input is flags

### ISSUE THREAD

**Issue by crezra** [withfig/autocomplete#1123]
### Description:
Sometimes when typing a command with arguments, I'm prompted to select a flag, which requires me to either press backspace or escape to cancel and close fig to run my command without flags.

Example : Here I am trying to run the `valet` command with `start` as argument, I press enter, then I'm prompted to select flags :  

https://user-images.githubusercontent.com/81156495/162406289-e0c19078-0536-4961-8568-7195a345f0c7.mp4

It would be nice it was possible to have fig enabled for primary arguments, for instance in this case have fig suggest `valet start` and if I want to select flags I can either press tab or another shortcut to have them shown to me.

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.3.1 (21E258)|1.0.56|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.56 (B421) [French]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/[REDACTED]/.nvm/versions/node/v17.2.0/bin:/Users/[REDACTED]/bin:/Users/[REDACTED]/.composer/vendor/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/[REDACTED]/.local/bin:/Users/[REDACTED]/.fig/bin:/Users/[REDACTED]/.local/bin:/Users/[REDACTED]/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro17,1
  - Chip: Apple M1
  - Cores: 8 (4 performance and 4 efficiency)
  - Memory: 16 GB
## OS Info:
  - macOS 12.3.1 (21E258)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/[REDACTED]/work

  - CLI Installed: true
  - Executable Location: /Users/[REDACTED]/.local/bin/fig
  - Current Window ID: 11186/% (com.googlecode.iterm2)
  - Active Process: zsh (25953) - /dev/ttys011
  - Environment Variables:
    - TERM_SESSION_ID=w0t2p0:7229E4DF-6ABE-42DA-9147-42BA992E458B
    - PATH=/Users/[REDACTED]/.nvm/versions/node/v17.2.0/bin:/Users/[REDACTED]/bin:/Users/[REDACTED]/.composer/vendor/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/[REDACTED]/.local/bin:/Users/[REDACTED]/.fig/bin:/Users/[REDACTED]/.local/bin:/Users/[REDACTED]/.local/bin
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: true

</p>
</details>

**Comment by fedeci** [comment]
Do you want to update the spec?

**Comment by codedbyjordan** [comment]
I can take a look at updating the spec
