### ISSUE TITLE
[rails] Autocomplete not showing up for Rails command

### ISSUE THREAD

**Issue by isghanim** [withfig/autocomplete#1151]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [ ] I would like to work on this.

### What CLI tool does this relate to?

rails

### Which statement makes the most sense?

There is a bug with this completion spec

### Issue Details

The issue is similar, but not identical, to [this issue](https://github.com/withfig/autocomplete/issues/870).

When I type `rails` I don't get autocomplete for it. It just loads forever. But a few times I saw a flash of autocomplete for the `rails new` command.

I am getting autocomplete for other commands, e.g. `ruby`.

**Ruby and Rails installations**
Since I'm on mac, I have to use [rbenv](https://github.com/rbenv/rbenv) to allow me to use an up-to-date ruby installation instead of the system version.

Since the system ruby version is outdated, I don't have Rails installed globally. Instead, I'm running rails when in the directory of my rails project after running `bundle install`.

Maybe the problem is that fig is having trouble locating the Rails installation?

----
Any idea what the issue could be?

**Comment by bolshoytoster** [comment]
@fedeci I have no clue, I don't even own a mac.

**Comment by fedeci** [comment]
I've just fixed it, sorry for the useless ping!

**Comment by fedeci** [comment]
Fixed in https://github.com/withfig/autocomplete/commit/adec64c7f39c774f882d7c9d1ef27b13eebf9af2

**Comment by isghanim** [comment]
Amazing! Thank you for the super fast turnaround :)
