### ISSUE TITLE
[Kubectl] "kubectl get nodes" autocompletes to "kubectl get --no-headers" 

### ISSUE THREAD

**Issue by jakemalachowski** [withfig/autocomplete#1155]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [ ] I would like to work on this.

### What CLI tool does this relate to?

kubectl

### Which statement makes the most sense?

Something else

### Issue Details

`kubectl get nodes` transforms to `kubectl get --no-headers` unless you escape the autocomplete. I think it would be preferable for Fig to prefer the fully-typed command rather than the partial match to a different command.

**Comment by mschrage** [comment]
Hey @jakemalachowski - is `nodes` a subcommand of `kubectl get`?

**Comment by jakemalachowski** [comment]
Hey @mschrage. Yes it is. I just noticed that `nodes` actually _does_ get suggested. It just takes ~5 seconds for the autosuggestion to update from `--no-headers` to `nodes`. I suspect that Fig is running `kubectl api-resources` behind the scenes to get a list of all resources, which takes some time.

**Comment by fedeci** [comment]
We can add a cache to the kubectl api-resources generator such that we get rid of those 5 seconds for a while @jakemalachowski Is `kubectl api-resources` data often refreshed? How much should it take for cache to expire? Note that we have `stale-while-revalidate` cache so we can keep lower cache expire time.

**Comment by fedeci** [comment]
Great! Can you give a look here https://fig.io/docs/reference/generator#cache to see if `cacheByDirectory` may work correctly? Sorry but I am totally out from the kubernetes world and have no idea of what a resource is.

**Comment by jakemalachowski** [comment]
No worries! In this case, the cache wouldn't be relevant to the directory a user is in
