### ISSUE TITLE
[ssh] Autocompletition for ssh is not working with Includes

### ISSUE THREAD

**Issue by danys94** [withfig/autocomplete#1187]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [ ] I would like to work on this.

### What CLI tool does this relate to?

ssh

### Which statement makes the most sense?

This completion spec isn't complete

### Issue Details

When you have config file in .ssh/ its being taken in account.
But when you put the below into your config
```
Host home*
  Include ~/.ssh/home.config
```
which contains other hosts, those hosts are not being taken in account to the autocomplete.

Could you please have a look at this? 

Thanks in advance. :-)

**Comment by EmranMR** [comment]
Hi I am not sure if my issue is related to this, however I dont seem to be able to get Fig working when I am accessing a remote machine (Mac -> linux) via SSH. Is this just an unsupported feature or there is a way to use fig on the remote machine as shown on fig.io homepage? Do I need to install any tools on the remote machine or local?

I read this troubleshooting article on the website but I can not find any documentation on how to integrate fig while in SSH. Not to mention what is discussed in the article seems to  be deprecated.

https://fig.io/support/troubleshooting/common-fixes/ssh

thanks 🙏
