### ISSUE TITLE
shift+tab should cycle through autocomplete in reverse order

### ISSUE THREAD

**Issue by amilajack** [withfig/autocomplete#119]
### Completion Spec

Fig itself

### Description

shift+tab should cycle through autocomplete in reverse order

### Steps to reproduce

Enable tab navigation:

```
fig settings autocomplete.tab navigate
```

Press shift and tab. It won't cycle in reverse order

### Expected result

Should cycle in reverse order

### Actual result

Cycled in normal order

**Comment by falky97** [comment]
@mattschrage The four ways of inserting text could be tab, shift tab, enter, and clicking... Each could be customisable?

**Comment by mattschrage** [comment]
@amilajack just pushed the fix! Make sure you're on build 1.0.40 and then toggle autocomplete off and on to reload it. :)
