### ISSUE TITLE
Warp

### ISSUE THREAD

**Issue by seabornlee** [withfig/autocomplete#1198]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [ ] I would like to work on this.

### What CLI tool does this relate to?

Warp

### Which statement makes the most sense?

Something else

### Issue Details

Hope supports Warp.
https://warp.dev

**Comment by favna** [comment]
Also going to up/follow this issue because I too would love to see Fig support Warp.

**Comment by SeparateRecords** [comment]
There's an issue for this in the main issue tracker: https://github.com/withfig/fig/issues/785 -- We mostly use this one for tracking suggestions for specific autocomplete specs 🙂

As it stands, warp currently uses this repo for their autosuggestions! (although my understanding is that that might change)
