### ISSUE TITLE
[helmfile] add completion spec

### ISSUE THREAD

**Issue by hashbou** [withfig/autocomplete#1201]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [ ] I would like to work on this.

### What CLI tool does this relate to?

helmfile

### Which statement makes the most sense?

This completion spec does not exist

### Issue Details

[helmfile](https://github.com/helmfile/helmfile) is another abstraction to helm and it would be great to have this spec in fig too. Thanks for you great work!

**Comment by mschrage** [comment]
Hey @hashbou! Are you working on a completion spec for `helmfile`? Let us know if you need any help :)

**Comment by Wail-Mohammed** [comment]
Hi everyone, hope you are all well. We are a small group of students that are interested in adding the completion spec for helmfile. It will be our first time at attempting something like this, we will do our best. Thank you!

**Comment by hashbou** [comment]
@Wail-Mohammed Thanks for taking over! Had no time to finish this up 🙈
