### ISSUE TITLE
[yarn] [npx] Suggest npm packages which install into `node_modules/.bin`

### ISSUE THREAD

**Issue by tpluscode** [withfig/autocomplete#1211]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [ ] I would like to work on this.

### What CLI tool does this relate to?

yarn, npx, npm

### Which statement makes the most sense?

This completion spec does not exist

### Issue Details

Many npm packages provide a CLI tool, defined by the [bin package.json field](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#bin)

It would be great if fig suggested at least the names of said binaries installed into local `node_modules`. This is supported by running `yarn [bin]` and `npx [bin]`.

I suppose this could work in one of two possible ways:

1. By introspecting the entire contents of closest `node_modules/.bin`
2. By analysing `package.json` only of packages explicitly listed in the local dependencies (preferred?)

As a stretch goal, it would be an absolute killer feature if individual packages would offer even more suggestion. (I hear that packages based on commander can be auto-completed too?)

**Comment by fedeci** [comment]
`npx` is already suggesting those executables located under .bin, I am adding that feature to yarn too!
