### ISSUE TITLE
[git] autocomplete on partial command names

### ISSUE THREAD

**Issue by tpluscode** [withfig/autocomplete#1217]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [ ] I would like to work on this.

### What CLI tool does this relate to?

git

### Which statement makes the most sense?

This completion spec isn't complete

### Issue Details

Not sure if this is a git-specific feature, but the git CLI is quite flexible in completing unambiguous command names.

For example, I typically type `git ut [TAB]` which gets natively autocompleted as `git checkout`. Similarly `git pick [TAB]` is unambiguously resolved as `git cherry-pick`

Fig, however, does not find that these match any command and only displayed the fallback "Custom user defined git alias" message which is not true.

**Comment by SeparateRecords** [comment]
This is actually a feature of the shell, not git specifically - run this command to enable the same behavior in fig!

```
fig settings autocomplete.fuzzySearch true
```

You might also want to change tab to insert the suggestion instead of the common prefix. I find this a lot more natural by YMMV

```
fig settings autocomplete.keybindings.tab insertSelected
```

**Comment by tpluscode** [comment]
Superb! Thanks

And what does `autocomplete.keybindings.tab` do? I don't understand

**Comment by SeparateRecords** [comment]
This changes the behavior of hitting tab. By default, it inserts a common prefix, eg. if you type `git st` and have `stash` and `status` as suggestions, `sta` is common between them, so it inserts that.

Setting tab to `insertSelected` means that whatever the highlighted suggestion is will be inserted. I find that this works a lot better with fuzzy search, but that's just my preference - there's lots of other actions you can use too 🙂

https://user-images.githubusercontent.com/52195359/168006863-c1cb25a0-ed2c-43de-88f6-6ad32b9b419a.mov

**Comment by tpluscode** [comment]
Gotcha, I was trying that with an unambiguous incomplete command so I was not seeing the behaviour.

**Comment by SeparateRecords** [comment]
Great thing about fuzzy search is that, regardless of whether you use `insertSelected` or not, you can usually make _any_ suggestion unambiguous in a few keystrokes 😄

<img width="425" alt="Screen Shot 2022-05-12 at 4 40 13 pm" src="https://user-images.githubusercontent.com/52195359/168007634-2efde073-e449-451d-86be-10e71c72db9a.png">

**Comment by tpluscode** [comment]
Indeed. Given that it's also a feature of zsh, I totally prefer that over aliases which I need to set up on every environment!
