### ISSUE TITLE
[pipenv]`pipenv -r` autocomplete is incorrect

### ISSUE THREAD

**Issue by anoushk1234** [withfig/autocomplete#1242]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [ ] I would like to work on this.

### What CLI tool does this relate to?

pipenv

### Which statement makes the most sense?

There is a bug with this completion spec

### Issue Details

pipenv -r should accept a path to requirements.txt but instead autocomplete suggests package names

**Comment by danieled-it** [comment]
Shouldn't this issue be closed after PR approval?

**Comment by SeparateRecords** [comment]
It should be! Dunno why it wasn't. Thanks for pointing it out 🙂
