### ISSUE TITLE
Descriptions show in a tooltip or some other method to see completely instead of side scrolling.

### ISSUE THREAD

**Issue by raguay** [withfig/autocomplete#127]
### Completion Spec
Any spec that has a long description.

### Description
A long description for a command or sub-command in a spec can be very long when they are gathered from an outside source (Mask descriptions for commands). For me, the side scrolling to view the entire description is a bit difficult to maneuver.

### Steps to reproduce
look at a description for and command that is long and you have to side scroll to see it all

**Comment by cstrnt** [comment]
Hey there 😊 
Thank you very much for providing a suggestion! We will work on that! Accessibility is really important 😄

**Comment by SeparateRecords** [comment]
Done!
