### ISSUE TITLE
Wrap suggestion descriptions to multiple lines

### ISSUE THREAD

**Issue by erikras** [withfig/autocomplete#128]
### Description
Describe the issue that you're seeing. [Slack thread](https://figcommunity.slack.com/archives/C01748QPHRN/p1618474036140900)

![image](https://user-images.githubusercontent.com/4396759/114897294-60c3a800-9e11-11eb-8ef5-62943bddc087.png)

### Expected result
Description should wrap to at least 2-3 lines.

**Comment by mattschrage** [comment]
See also #127
