### ISSUE TITLE
[yarn] version missing commands

### ISSUE THREAD

**Issue by ShawnCockburn** [withfig/autocomplete#1285]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [X] I would like to work on this.

### What CLI tool does this relate to?

yarn

### Which statement makes the most sense?

This completion spec isn't complete

### Issue Details

(Note to self, I will fix this: @ShawnCockburn )

yarn version missing auto complete commands

also check for other missing yarn commands

**Comment by fedeci** [comment]
Since yarn 1 is very different from yarn 2 and 3

**Comment by ShawnCockburn** [comment]
> Actually we should start using diff-versioned specs for yarn

I was referring to version yarn `1.22.15`.

I just had a look at the documentation on the website and I couldn't find much info about diff-versioned specs and how to use/make them, could you point me in the right direction?

Thank you mate!

**Comment by ShawnCockburn** [comment]
@fedeci @SeparateRecords ^^^ bump ^^^

**Comment by fedeci** [comment]
Thanks for pinging me (always ping me as I tend to be overwhelmed by notifications and often forget something)!
I believe we need to document diff-versioned specs, for the moment just update the current spec which is actually yarn@1 with some commands from later versions!

**Comment by ShawnCockburn** [comment]
will do, thanks!

**Comment by joeheyming** [comment]
I can take this, but I'm not sure how many arguments need to be added to the spec

**Comment by joeheyming** [comment]
https://github.com/withfig/autocomplete/pull/1606

**Comment by brendanfalk** [comment]
This was fixed with the above merges. Closing
<img width="874" alt="CleanShot 2022-11-23 at 10 45 10@2x" src="https://user-images.githubusercontent.com/4949076/203624406-650c7469-2ade-4f26-a076-73348fb29cdf.png">
