### ISSUE TITLE
[GIT]: Git completion is missing --force-with-lease option.

### ISSUE THREAD

**Issue by odrotbohm** [withfig/autocomplete#136]
See summary.

**Comment by mattschrage** [comment]
To confirm, this is an optional flag under [git push](https://git-scm.com/docs/git-push)?

**Comment by odrotbohm** [comment]
Yes, see [the documentation for details](https://git-scm.com/docs/git-push). It does a ref comparison and only issues the force if the remote ref hasn't changed. That's why it's to be preferred over a plain force. Often not used as it's quite a few keystrokes more, something Fig can nicely help with. 🙃

**Comment by cstrnt** [comment]
Hey there @odrotbohm!
This is currently being worked on in #215

**Comment by nirtamir2** [comment]
I think I fixed this issue specifically by https://github.com/withfig/autocomplete/pull/238

**Comment by falky97** [comment]
Closing this as it appears to be fixed! Thank your @nirtamir2  :)

**Comment by odrotbohm** [comment]
Lovely! Thanks, folks! 🙇‍♂️
