### ISSUE TITLE
Suggestion window height is constant for git and ssh

### ISSUE THREAD

**Issue by gelpenaddict** [withfig/autocomplete#137]
### Description:
I set the height to 1000 and the window size is now constant rather than form-fitting for git and ssh. It does form-fit for fig.
<img width="333" alt="Screen Shot 2021-04-21 at 8 36 50 AM" src="https://user-images.githubusercontent.com/6164318/115581349-c930e000-a27c-11eb-8480-2ef4d2c4dcbc.png">

 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|10.16.0|Version 1.0.40 (B188)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.40 (B188)
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/carlowan/.fig/bin/fig
Accessibility: true
Number of specs: 77
SSH Integration: true
Tmux Integration: true
Keybindings path: /Users/carlowan/.fig/user/keybindings
iTerm Integration: true
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (96635) - ttys001
Current working directory: /Users/carlowan
Current window identifier: 36075/1C2C1D59C-338A-42CB-B136-F3FCF145C696% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by falky97** [comment]
Okay, you're actually not going to believe this, this is an issue with the way we implement virtual scrolling. If you use your mouse and scroll 1px in the git case, all of the commands will actually appear and you will see that Fig does actually form fit. 

We built virtualisation way before we had the ability to change window height so just totally missed this. We will fix!!

**Comment by falky97** [comment]
I believe this is fixed @gelpenaddict can you confirm for us?  Make sure you are on the latest version of Fig


Please comment and we will reopen if not.
