### ISSUE TITLE
Developer mode enabled can't be disabled

### ISSUE THREAD

**Issue by thomasverleye** [withfig/autocomplete#1421]
### Sanity checks

- [ ] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [ ] I would like to work on this.

### What CLI tool does this relate to?

anything

### Which statement makes the most sense?

Something else

### Issue Details

I'm constantly seeing this popup, I am not able to disable this.
<img width="525" alt="Screenshot 2022-08-17 at 16 02 35" src="https://user-images.githubusercontent.com/2844485/185154021-6837e059-167f-489e-be5b-faa479943208.png">

**Comment by vitormalencar** [comment]
@thomasverleye  how did you solve this issue?

**Comment by AaronDovTurkel** [comment]
I am having the same issue.

**Comment by betraying** [comment]
+1

**Comment by thomasverleye** [comment]
@vitormalencar @AaronDovTurkel @betraying see https://github.com/withfig/fig/issues/1695
Posted in the wrong repository :-)

**Comment by JamesBissick** [comment]
Same issue, annoying warning message that can't be disabled.

**Comment by SeparateRecords** [comment]
Hey all! This is fixed now, just run `fig restart` 🙂

Also as @thomasverleye noted, https://github.com/withfig/fig is our bug tracker, this repo is exclusively used for completion-related bugs / requests
