### ISSUE TITLE
[pm2] request for spec

### ISSUE THREAD

**Issue by mpekala23** [withfig/autocomplete#144]
### CLI Tool
pm2

### Useful Links
https://pm2.keymetrics.io/docs/usage/quick-start/

### Top Workflows
`pm2 start`
`pm2 restart all`
`pm2 stop`

**Comment by cstrnt** [comment]
Hey there @mpekala23 
that's a good one! Are you proficient with PM2 and would be willing to create it yourself? This would be highly appreciated :)

**Comment by QuiiBz** [comment]
Merged in #338, thanks everyone!
