### ISSUE TITLE
Autocompletion when using ENV variables.

### ISSUE THREAD

**Issue by tcK1** [withfig/autocomplete#146]
### Completion Spec
Fig itself? I don't really know, sorry! :see_no_evil: 

### Description
When using ENV variables before any command, the autocomplete stops working.

### Steps to reproduce
* FIG should be running;
* Open any configured terminal;
* Type `ENV=1` or any combination of `{name}={value}`;
* Start typing the actual command.

### Expected result
We should see the autocomplete window for what I'm typing.

### Actual result
![image](https://user-images.githubusercontent.com/9873486/116091044-dda91a00-a67a-11eb-8380-88ac1b101f65.png)

**Comment by mattschrage** [comment]
Thanks for creating the issue! I think this is pretty doable.

**Comment by fedeci** [comment]
Yes, this is really annoying especially when dealing with commands that make heavy use of ENV vars.

**Comment by ericboucher** [comment]
I found this issue on https://ovio.org/projects and would love to contribute. Any thoughts or pointers @mschrage ?

**Comment by fedeci** [comment]
It is part of the internal autocomplete engine, which is not open source.

**Comment by ericboucher** [comment]
Oh, sad... Any idea when this might get addressed?

**Comment by SeparateRecords** [comment]
Unblocked now! Generators have access to env vars

**Comment by SeparateRecords** [comment]
Misread, different issue. But this is also done because @fedeci is awesome
