### ISSUE TITLE
Add `gem` completion spec

### ISSUE THREAD

**Issue by AlanSyue** [withfig/autocomplete#1478]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [X] I would like to work on this.

### What CLI tool does this relate to?

gem

### Which statement makes the most sense?

This completion spec does not exist

### Issue Details

reference: https://guides.rubygems.org/command-reference/

**Comment by SeparateRecords** [comment]
Generator for listing gems:
```ts
const gems: Fig.Generator = {
  custom: async (tokens, executeShellCommand) => {
    const searchTerm = tokens[tokens.length - 1];
    const out = await executeShellCommand(
      `gem search --both --no-versions --no-details '${searchTerm.replace("'", `'"'"'`)}'`,
    );
    return out.trim().split("\n")
      .filter((line) => line && !line.startsWith("*"))
      .map((name) => ({ name }));
  },
};
```

Make sure you put `debounce: true` on the arg containing the generator!

**Comment by AlanSyue** [comment]
OK, thanks! I'd love to work on it.
