### ISSUE TITLE
Add `phpunit` completion spec

### ISSUE THREAD

**Issue by AlanSyue** [withfig/autocomplete#1484]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [X] I would like to work on this.

### What CLI tool does this relate to?

phpunit

### Which statement makes the most sense?

This completion spec does not exist

### Issue Details

reference: https://phpunit.readthedocs.io/en/9.5/textui.html#command-line-options

**Comment by rubynguyen1510** [comment]
I am working on this.

**Comment by rubynguyen1510** [comment]
A pull request to solve this issue was been submitted here: https://github.com/withfig/autocomplete/pull/1824.
