### ISSUE TITLE
Fuzzy search for zsh

### ISSUE THREAD

**Issue by arthurjdam** [withfig/autocomplete#151]
### Completion Spec

Enhancement to fig's overall autocompletion. It's not mission-critical but since I'm so used to how zsh's autocomplete works, I feel like it should at least be put up for consideration.

### Description

For zsh the tabbed autocomplete uses a fuzzy search, instead of fig's current substr-style.

### Steps to reproduce

Using oh-my-zsh, go to a folder. For example containing the following:
```bash
~ ls
project-name-one
project-name-two
~ cd two
```

### Expected result

If you now press "tab", it will auto-complete to `project-name-two`

### Actual result

In this scenario, Fig would show no available autocompletions

**Comment by mattschrage** [comment]
Hey @arthurjdam! Thanks for the suggestion. We actually have implemented this already! Right now it's behind a feature flag because there are still a few things left to fix.

If you would look to try it out, you can run:
`fig settings autocomplete.fuzzySearch true`

**Comment by arthurjdam** [comment]
Works as expected! Thanks @mattschrage !
