### ISSUE TITLE
[yarn] Missing `why` subcommand

### ISSUE THREAD

**Issue by MengsokunVeng** [withfig/autocomplete#1615]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [X] I would like to work on this.

### What CLI tool does this relate to?

yarn

### Which statement makes the most sense?

This completion spec does not exist

### Issue Details

Missing yarn why spec option (-R or --recursive) & (--peers)

**Comment by brendanfalk** [comment]
This has been fixed!
<img width="841" alt="CleanShot 2022-11-23 at 10 44 35@2x" src="https://user-images.githubusercontent.com/4949076/203624280-4e14e472-e7b3-46d3-93a6-10527fc483df.png">
