### ISSUE TITLE
[curl] Missing `--ssl-auto-client-cert` option

### ISSUE THREAD

**Issue by MengsokunVeng** [withfig/autocomplete#1618]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [X] I would like to work on this.

### What CLI tool does this relate to?

curl

### Which statement makes the most sense?

This completion spec does not exist

### Issue Details

Add curl options --ssl-auto-client-cert to use and obtains a client certificate automatically from url link.

**Comment by mrhappyma** [comment]
This can be closed
![screenshot](https://botnet.lol/%F0%9F%93%B8/%E2%81%A0%E2%80%8B%E2%80%8B%E2%81%A0%E2%80%8D%E2%80%8B%E2%80%8D%E2%81%A0%E2%81%A0%E2%80%8C%E2%80%8D%E2%80%8D%E2%80%8D%E2%81%A0%E2%80%8B%E2%80%8C%E2%80%8B%E2%80%8C%E2%80%8D%E2%80%8C%E2%80%8B%E2%80%8D%E2%80%8C%E2%81%A0%E2%81%A0%E2%80%8B%E2%80%8D%E2%81%A0%E2%80%8D%E2%81%A0%E2%80%8B)
