### ISSUE TITLE
[gum] missing commands from 0.8

### ISSUE THREAD

**Issue by SeparateRecords** [withfig/autocomplete#1619]
https://github.com/charmbracelet/gum/releases/tag/v0.8.0

**Comment by SeparateRecords** [comment]
@Fall1ngStar would you be interested in working on this?

**Comment by Fall1ngStar** [comment]
Yeah I'll find some time to do that 😃

**Comment by SeparateRecords** [comment]
Awesome! Will assign this to you. No worries if you don't have the time, october's a busy month!

**Comment by Fall1ngStar** [comment]
MR created !

**Comment by SeparateRecords** [comment]
Legend! Thank you 😄
