### ISSUE TITLE
[CLI_NAME] Missing `gatsby` info `-C, --clipboard` spec

### ISSUE THREAD

**Issue by MengsokunVeng** [withfig/autocomplete#1624]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [X] I would like to work on this.

### What CLI tool does this relate to?

gatsby

### Which statement makes the most sense?

This completion spec does not exist

### Issue Details

Missing gatsby info spec ( -C, --clipboard )

**Comment by Gautam-Arora24** [comment]
Would like to work on this.

**Comment by Gautam-Arora24** [comment]
We already have this command in gatsby's spec. You can find it [here](https://github.com/withfig/autocomplete/blob/master/src/gatsby.ts#L90). This issue can be closed in my opinion.
