### ISSUE TITLE
[ditto] missing spec

### ISSUE THREAD

**Issue by SeparateRecords** [withfig/autocomplete#1641]
See `man ditto`

**Comment by vatana7** [comment]
I've made a PR for this. Please check it @SeparateRecords

**Comment by mschrage** [comment]
Hey @vatana7! It looks like you added this the the `man` spec rather than creating a new spec for `ditto`.

@SeparateRecords was suggesting that you could use the `man` command to see all of the options and arguments that `ditto` takes.

**Comment by vatana7** [comment]
Okay thanks. I'll look into it

**Comment by vatana7** [comment]
@mschrage Hey I've committed some changes on the issues you mentioned. Can you take a look?
