### ISSUE TITLE
[curl] Missing args `--etag`, `--fail-with-body`

### ISSUE THREAD

**Issue by MengsokunVeng** [withfig/autocomplete#1680]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [X] I would like to work on this.

### What CLI tool does this relate to?

curl

### Which statement makes the most sense?

This completion spec does not exist

### Issue Details

There are some missing specs in curl cli.

**Comment by mrhappyma** [comment]
I couldn't find any documentation or reference to either of these options, is there a good source that does have them?

**Comment by mbd-s** [comment]
@mrhappyma 

> I couldn't find any documentation or reference to either of these options, is there a good source that does have them?

The [man page](https://curl.se/docs/manpage.html) for `curl` lists `--fail-with-body` and two ETag options (`--etag-compare` and `--etag-save`) 🙂
