### ISSUE TITLE
[cd][fig_cli 2.5.3] Missing the "red" enter option for opening the specific folder

### ISSUE THREAD

**Issue by andreiverdes** [withfig/autocomplete#1683]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [ ] I would like to work on this.

### What CLI tool does this relate to?

cd

### Which statement makes the most sense?

There is a bug with this completion spec

### Issue Details

Missing the "red" ↩️ enter option for opening the specific selected folder

**Comment by andreiverdes** [comment]
<img width="435" alt="Screenshot 2022-10-27 at 14 10 28" src="https://user-images.githubusercontent.com/702346/198273594-d0c1624c-14c9-4f99-8f14-7dcfabc1b526.png">

**Comment by grant0417** [comment]
This should be resolved now!
