### ISSUE TITLE
[`man`] backslash added to autocomplete options

### ISSUE THREAD

**Issue by mrhappyma** [withfig/autocomplete#1735]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [ ] I would like to work on this.

### What CLI tool does this relate to?

man

### Which statement makes the most sense?

There is a bug with this completion spec

### Issue Details

https://user-images.githubusercontent.com/55963440/206053577-3d71ec5b-29fe-4f4c-8832-aa17c5837a04.mp4

**Comment by Gautam-Arora24** [comment]
Couldn't reproduce on my end. Could you please share environment details/logs?
