### ISSUE TITLE
Handle case where a variadic argument is followed by another different argument.

### ISSUE THREAD

**Issue by mschrage** [withfig/autocomplete#177]
Currently, if a variadic argument is followed by another argument (`[ arg1... ] [ arg2 ]`), the second argument will never be prompted by Fig's autocomplete.

**Expected behavior:** After the first that satisfies `arg1` is inserted, Fig should show suggestions for both `arg1` and `arg2`.

**Comment by SeparateRecords** [comment]
Pretty sure this is (sort of?) resolved now
