### ISSUE TITLE
Duplicate `example`, `examples` and `_examples` folder in specs

### ISSUE THREAD

**Issue by QuiiBz** [withfig/autocomplete#180]
### Completion Spec

`master` branch issue

### Description

The `specs` directory contains two identic folders, `_examples` and `examples` which exist by default, and a third one: the `example` folder which is generated after the `build` command

### Steps to reproduce

Run the `build` script and open the `specs` folder

### Expected result

There should be only one example folder

### Actual result

There are three folders, `_examples` and `examples` which exist by default, and `example` which is generated after the `build` command

### Potential Solution

Delete the `specs/_examples` and `specs/examples` folders,  and run the `build` script once to generate the examples in the `specs/example` directory

### Screenshots
`specs` directory by default in the `master` branch:
![Screenshot 2021-05-05 at 08 56 17](https://user-images.githubusercontent.com/43268759/117106210-c2779200-ad7f-11eb-8fd6-839af58006a8.png)

After running the `build` script:
![Screenshot 2021-05-05 at 08 56 37](https://user-images.githubusercontent.com/43268759/117106237-ce635400-ad7f-11eb-812c-14c0181f7070.png)

**Comment by cstrnt** [comment]
Hey Tom :) We just merged #221 which removes the `specs` folder from the git index and thus removes this problem as well :)
