### ISSUE TITLE
Do not suggest the same option after it has been already autocompleted

### ISSUE THREAD

**Issue by nagypeterjob** [withfig/autocomplete#183]
### Completion Spec
What completion spec does this enhancement refer to? Or is it Fig itself?
Fig itself

### Description
Currently fig suggest the same option as many times as one types --<option>

example:
command subcommand --option1 foo --option1 

Describe the issue that you're seeing.

### Steps to reproduce
Clear steps describing how to reproduce the issue. **Please** link to a reproduction, this makes your issue _much_ easier to diagnose (seriously).

### Expected result
What should happen?
If an option has been already autocompleted, do not suggest it again

### Actual result
What happened.

**Comment by SeparateRecords** [comment]
Implemented now, options are only repeatable is `isRepeatable` is set
