### ISSUE TITLE
[shopify-cli] Update Spec

### ISSUE THREAD

**Issue by rayy-lo** [withfig/autocomplete#1852]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [X] I would like to work on this.

### What CLI tool does this relate to?

shopify-cli

### Which statement makes the most sense?

This completion spec isn't complete

### Issue Details

Shopify introduced a new major version for their cli. Their old version will become legacy at the end of May. The new version introduces a lot of changes (new commands, flags...) and it would be nice to update the spec.

**Comment by fedeci** [comment]
Thanks for the effort @rayy-lo, can you please use [diff-versioned specs](https://fig.io/docs/concepts/advanced-specs#diff-versioned-specs)?

Ping me here or (even better) on discord if you need help!
