### ISSUE TITLE
[k6] missing autocomplete for `version`

### ISSUE THREAD

**Issue by BalduinLandolt** [withfig/autocomplete#1921]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [ ] I would like to work on this.

### What CLI tool does this relate to?

k6

### Which statement makes the most sense?

This completion spec isn't complete

### Issue Details

`k6 version` seems to be missing. I haven't checked others, this just struck my eye.

Probably not the most important command, but maybe still nice to have

**Comment by oscarsjlh** [comment]
Hi 

I would like to tackle this one.

**Comment by fedeci** [comment]
Hello @oscarsjlh, I'll assign you to the issue, since it is your first contribution to the repo I suggest you to read the [docs](https://fig.io/docs/getting-started) and to give a look at the other completion specs. For any question please tag me!
