### ISSUE TITLE
Could this be an extension used by another completion tool (like Oh My Zsh) ?

### ISSUE THREAD

**Issue by Yohannfra** [withfig/autocomplete#193]
Hello, 
I'm wondering if this tool could be used as an external ui for the autocompletion of Oh My Zsh (or any shell).

Thanks

**Comment by mattschrage** [comment]
Potentially! We are focused on 'first-party' completions for the moment since they can take full advantage of Fig completion standard (with descriptions, icons, etc.) but we definitely want to incorporate existing shell completions as well!

**Comment by SeparateRecords** [comment]
Going to close this as out of scope - we have **over 500** completions now, and you can also really quickly contribute them to this repo or build your own for private/team use.

That's not to say we won't do this eventually, but for now we don't have any plans for it 🙂
