### ISSUE TITLE
cd supports the resident option

### ISSUE THREAD

**Issue by cycle2zhou** [withfig/autocomplete#1938]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my feature

### Description:
Currently, the cd command does not prompt for ~, but we will be entering this directory frequently, so we want to keep cd ~ on the prompt

**Comment by fedeci** [comment]
@cycle2zhou you can implement this a a suggestion in the `cd` spec and open a PR. Please ping me for any question!

**Comment by cycle2zhou** [comment]
What can be done? Personalization?

**Comment by Gautam-Arora24** [comment]
Working on this.
