### ISSUE TITLE
[cd] Is there an option to disable the CD preview feature in the configuration settings?

### ISSUE THREAD

**Issue by jsonleex** [withfig/autocomplete#1963]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [ ] I would like to work on this.

### What CLI tool does this relate to?

cd

### Which statement makes the most sense?

Something else

### Issue Details

I noticed a cool CD preview feature was added for autocomplete in #1956, the preview feature is pretty cool, but for privacy concerns, sometimes I need to disable it temporarily.

Is there an option to disable the CD preview feature in the configuration settings?

<img width="571" alt="iShot_2023-05-12_14 07 35" src="https://github.com/withfig/autocomplete/assets/25883665/c344f20a-0cda-4e94-a193-2088435e326f">

**Comment by fedeci** [comment]
@jsonleex In case you are still incurring in this issue, this disables it `fig settings autocomplete.hidePreviewWindow true`.
