### ISSUE TITLE
Fig won't work on Warp terminal.

### ISSUE THREAD

**Issue by firebyou** [withfig/autocomplete#1972]
When will Fig be supported?

**Comment by alanhg** [comment]
@firebyou 

just have a try.
![image](https://github.com/withfig/autocomplete/assets/9245110/13b81779-be0b-4a7e-b1fc-52c89a4e1bfa)

**Comment by alanhg** [comment]
> See https://github.com/withfig/fig/issues/785

so This is not possible as Warp is closed source？
