### ISSUE TITLE
Slack issue template link goes to a 404

### ISSUE THREAD

**Issue by OmgImAlexis** [withfig/autocomplete#204]
Currently when going to make an issue a link is provided to slack "https://waitlist.withfig.com/waitlist". This link currently returns nothing more than a white page with "Cannot GET /waitlist".

P.S. It might be worth looking at using Discord instead of Slack.

**Comment by cstrnt** [comment]
Hello Alexis,

thank you very much for reporting this :)
I just fixed this :)

And regarding Discord, thanks for the hint, we might be working on something secret right now 😉
