### ISSUE TITLE
Completions for code-insiders

### ISSUE THREAD

**Issue by Tyriar** [withfig/autocomplete#212]
### CLI Tool
`code-insiders` is the Insiders build of VS Code, this is almost always identical to the `code` spec.

This is blocked by https://github.com/withfig/autocomplete/issues/209, unless we want a bunch of duplication.

**Comment by cstrnt** [comment]
@Tyriar you can actually use the [`loadSpec`](https://fig.io/docs/autocomplete/schemas/subcommand#loadspec) property to load this in from your newly-created `code` spec. Would you be willing to do this? :) Seems like your an expert in terms of vscode 😊

**Comment by Tyriar** [comment]
@cstrnt I actually tried to do this today but it wasn't getting picked up. Does `npm run dev` play nicely with new specs?

**Comment by cstrnt** [comment]
@Tyriar I'm sorry, you are right! Apparently `loadSpec`only works with `subcommands` and not with the root command object! I'll create an issue 😄
