### ISSUE TITLE
[FIG] Template: "folders" shows files and folders when using variadic flag

### ISSUE THREAD

**Issue by cstrnt** [withfig/autocomplete#219]
### Completion Spec
Fig itself

### Description
When using `template: "folders"` and using `variadic: true` at the same time causes fig to show folders and files (see #211)

### Steps to reproduce
```ts
export const someCompletionSpec: Fig.Spec = {
  name: "test",
  options: [
    {
      name: "--some-option",
      template: "folders",
      variadic: true,
    },
  ],
};

```

### Expected result
Only folders are shown as suggestions

### Actual result
Files and folders are shown

**Comment by falky97** [comment]
Yes - variadic arguments of options have been causing some issues. I will look into what is going on here
