### ISSUE TITLE
[DOTSLASH] Prioritize executable files

### ISSUE THREAD

**Issue by Tyriar** [withfig/autocomplete#220]
**Is your feature request related to a problem? Please describe.**

Normally in bash the .bat file would be ignored when tabbing this because it's not executable:

![](https://user-images.githubusercontent.com/2193314/118982937-c2a39000-b930-11eb-8e48-c45f916a5d1d.png)

**Describe the solution you'd like**

I'd like the file to still show up but as a deprioritized option:

![image](https://user-images.githubusercontent.com/2193314/118983227-0e563980-b931-11eb-81e1-c3134ed22449.png)

**Comment by QuiiBz** [comment]
Merged in #290, thank you all!
