### ISSUE TITLE
[wp-cli] Add autocomplete for WP-CLI (WordPress command-line interface)

### ISSUE THREAD

**Issue by rosswintle** [withfig/autocomplete#222]
### CLI Tool
> What CLI tool is missing autocompletion in Fig?

I can't see that you have autocomplete for the WordPress command-line interface tool: https://wp-cli.org

### Useful Links
> Please add some links to the docs of that tool or the `--help`text

Commands are listed and documented at: https://developer.wordpress.org/cli/commands/

The commands documentation is auto-generated from the code comments for the commands. See, for example: https://github.com/wp-cli/config-command/blob/master/src/Config_Command.php

Each command is in a separate repo at: https://github.com/wp-cli/ (look for repos with names like "*-command")

Docs on the structure of the code comments that generate the docs and command lists are in the [Commands Cookbook](https://make.wordpress.org/cli/handbook/guides/commands-cookbook/#annotating-with-phpdoc)

Generated docs for commands are also in GitHub: https://github.com/wp-cli/handbook/tree/master/commands

It's worth noting that WP-CLI is extendable with both [packages](https://make.wordpress.org/cli/handbook/guides/commands-cookbook/#distribute-as-a-stand-alone-command) (that directly extend WP-CLI - this adds a command to the CLI for ALL sites) and [as part of plugins or themes](https://make.wordpress.org/cli/handbook/guides/commands-cookbook/#include-in-a-plugin-or-theme) that you install into WordPress sites (this only affects CLI usage on the site that the plugin/theme is installed in).

### Top Workflows
> What are the most used commands or workflows in that CLI tool (for you)?

`wp core download`
`wp core config --prompt`
`wp core install --prompt`

`wp db export`
`wp db import`

`wp search-replace <old-string> <new-string>`
`wp search-replace <old-string> <new-string> --all-tables`
`wp search-replace <old-string> <new-string> --dry-run`

`wp cache flush`

`wp core update`
`wp plugin list`
`wp plugin install <plugin>`
`wp plugin update <plugin>`
`wp plugin update --all`
`wp plugin activate <plugin>`
`wp plugin deactivate <plugin>`
`wp theme update <theme>`
`wp theme update --all`

`wp media regenrate`

`wp shell`
`wp db cli`

**Comment by danielpost** [comment]
+1, this would be great to have.

**Comment by schlessera** [comment]
WP-CLI provides the following tools to simplify building an integration:

#### `wp cli cmd-dump` & `wp cli param-dump` commands

These commands produce a JSON array with a dump of all the internal knowledge about the registered (sub)commands and the registered global parameters, respectively. The dump already includes all of the active extensions via the package manager.

#### `wp cli completion` command

This command lets you provide a string to be executed (which can be a full or only a partial command), as well as the position of the cursors, and it will then return a list of available autocomplete options.

**Comment by schlessera** [comment]
Ah, one other thing that can help:
When the documentation is updated, it also generates a manifest file that contains the structure of the command reference with links to the docs and the repos:

https://github.com/wp-cli/handbook/blob/master/bin/commands-manifest.json

**Comment by Monkeyank** [comment]
#285
