### ISSUE TITLE
`loadSpec` doesn't work for root commands

### ISSUE THREAD

**Issue by cstrnt** [withfig/autocomplete#223]
### Completion Spec
Fig itself

### Description
As described in #212, the `loadSpec` property isn't picked up if its used in the root object of the spec

### Steps to reproduce
```ts
export const completion: Fig.Spec = {
  name: "code-insiders",
  description: "",
  loadSpec: "code",
};

```

### Expected result
The spec should be loaded just like it works with subcommand

### Actual result
No suggestions are shown

**Comment by Monkeyank** [comment]
Closed with #388 

You can now use `import`!
