### ISSUE TITLE
Support spf13/cobra CLI generated completions

### ISSUE THREAD

**Issue by dfreilich** [withfig/autocomplete#228]
### Completion Spec
What completion spec does this enhancement refer to? Or is it Fig itself?
Fig (?) 

### Description
Many Golang CLIs use https://github.com/spf13/cobra as a framework for their CLIs. Cobra itself has a mechanism for generating code completions (documented here: https://github.com/spf13/cobra/blob/master/shell_completions.md). It would be great if there could be an easy tie in between that framework and fig, so that we could, for instance, run
`<cmd> completion --shell fig` upon every release, and upload that to `fig` to ensure that our CLI completion has (a) native Fig support, and (b) is never out of date with the current release. 

I'm very excited to hear about this project (I'm a maintainer for http://github.com/buildpacks/pack/, and am definitely interested in having a native Fig integration), and I hope that it's made easy for popular Golang CLIs!

**Comment by cstrnt** [comment]
Hey there :)
We were trying to generate a cobra parser ourselves, but adding that to cobra itself would be pretty awesome as well! 
Thank you very much for your feedback :)
