### ISSUE TITLE
Add autocomplete support for rclone

### ISSUE THREAD

**Issue by rmorey** [withfig/autocomplete#231]
### CLI Tool

`rclone` syncs files to and from cloud storage providers as well as mounting them, listing them in lots of different ways.

### Useful Links

- [Homepage](https://rclone.org)
- [GitHub](https://github.com/rclone/rclone)
- [CLI Documentation](https://rclone.org/docs/)
- [`--help` text](https://github.com/rclone/rclone/blob/master/docs/content/commands/rclone.md)

### Top Workflows

- `rclone config`
- `rclone listremotes`
- `rclone lsd remote:path`
- `rclone -P --exclude '.*{/**,}' sync /Volumes/Data/ remote:Data`
- `rclone mount remote: dir`

**Comment by rmorey** [comment]
Working on this here: https://github.com/rmorey/autocomplete/blob/rmorey/rclone/dev/rclone.ts

**Comment by rmorey** [comment]
What I've done so far is just transform the list of commands with descriptions from the help text into the spec format with `args: {}` for all. So this gets us simple autocomplete for every command, but nothing else - @cstrnt is this substantial enough for a PR?

**Comment by cstrnt** [comment]
Hey @rmorey that's awesome! 
Thank you very much for starting! 😊 
While it is totally fine for a spec to just be a skeleton to get merged in, I think this needs some little tweaks.

`args: {}` tells Fig that the command takes an argument. One example for this would be `cd folderName` where `cd`is the name of the command itself and `folderName` the argument which is passed to the command itself. I just looked up `rclone` and saw that not all commands take an argument like that. It would be really cool if you could remove `args: {}` for the commands which don't take an argument. If this is done it would be awesome if you would create a PR :)

Again, thank you very much for your effort and your time! And also let me know if you need some help :)

**Comment by cstrnt** [comment]
Also this page is a really good read 😆 
https://fig.io/docs/concepts/cli-skeleton

**Comment by rmorey** [comment]
> `args: {}` tells Fig that the command takes an argument. ... It would be really cool if you could remove `args: {}` for the commands which don't take an argument. If this is done it would be awesome if you would create a PR :)

Ahhhh, I misread the comment in the boilerplate! I missed the conditional in "*If a subcommand or option takes an argument*, you must include the args prop, even if it's an empty object (like below)" I'll remove those and submit a PR.

> Also this page is a really good read 😆
> https://fig.io/docs/concepts/cli-skeleton

Glad you fixed the link! 😜 (https://twitter.com/RyanMorey/status/1397581270817837061)

> Again, thank you very much for your effort and your time! And also let me know if you need some help :)

Glad to help! Fig is a great tool, happy to contribute

**Comment by cstrnt** [comment]
No worries! This might be a good sign, that we have to update the text to make it more clear!

Thanks for reporting the broken link as well 😆
