### ISSUE TITLE
[cd] spaces aren't escaped in cd's suggestions

### ISSUE THREAD

**Issue by cpendery** [withfig/autocomplete#2318]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [ ] I would like to work on this.

### What CLI tool does this relate to?

cd

### Which statement makes the most sense?

There is a bug with this completion spec

### Issue Details

When suggesting a path for cd with spaces in in the folder, fig doesn't include the escapes in the insertValue.

**Comment by mschrage** [comment]
Thanks for reporting this @cpendery! In this case, escaping should be implemented by the "autocomplete engine" rather than the completion spec. [Obviously, this is not documented anywhere. We should really codify these expectations!]

cc @grant0417

**Comment by grant0417** [comment]
Hey @cpendery can you give an example? Recording a video or photo would help here.
