### ISSUE TITLE
File path suggestions don't include intermediate folder paths

### ISSUE THREAD

**Issue by golergka** [withfig/autocomplete#234]
#### Steps to reproduce:
1. Open a folder with some modified files in a sub-folder
1. Type `git add -- `
1. Look at suggestions

#### Expected result:
The name of the sub-folder on the list, so I can add the whole sub-folder with all the modified paths

#### Actual result:
Only individual files appear on the suggestion list

#### Video:
https://user-images.githubusercontent.com/929735/119543011-dcadfa00-bd98-11eb-81a7-cfc9831866b2.mov

#### Discussion:
It may vary by person, but I often find myself referencing whole folders with programs such as git. I think that if my input matches one of the modified files, suggestions should have not only the full file path, but also all intermediate paths, as well.

### Details:
|macOS|Fig|Shell|
|----|----|----|
|11.2.3|Version 1.0.42 (B207)|/bin/zsh|

<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.42 (B207) 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/golergka/.fig/bin/fig
Accessibility: true
Number of specs: 107
SSH Integration: true
Tmux Integration: true
Keybindings path: /Users/golergka/.fig/user/keybindings
iTerm Integration: true
Hyper Integration: false
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (50819) - ttys000
Current working directory: /Users/golergka/Projects/fastcup/backend/backend-common
Current window identifier: 128250/13E08B25B-5092-47CA-9C6D-B5038A755BEB% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by mattschrage** [comment]
This has finally been fixed! Thanks for your patience @golergka :)

 https://github.com/withfig/autocomplete/pull/358
