### ISSUE TITLE
Autocomplete for git diff only shows commit as parameter

### ISSUE THREAD

**Issue by edolfo** [withfig/autocomplete#235]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Autocomplete for `git diff` shows `commit` as the only option

![image](https://user-images.githubusercontent.com/1239043/119575780-65fb0780-bd6c-11eb-916c-34543bfb2ff6.png)

Typically I will run `git diff` on individual files instead of entire changesets.

 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|10.15.7|Version 1.0.42 (B207)|/usr/local/bin/fish|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.42 (B207) 
UserShell: /usr/local/bin/fish
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/edolfo.garzalicudine/.fig/bin/fig
Accessibility: true
Number of specs: 107
SSH Integration: false
Tmux Integration: true
Keybindings path: /Users/edolfo.garzalicudine/.fig/user/keybindings
iTerm Integration: false
Hyper Integration: false
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by hiradp** [comment]
@mattschrage I'd like to give this a go.
