### ISSUE TITLE
[VOLTA] Add autocomplete support

### ISSUE THREAD

**Issue by nirtamir2** [withfig/autocomplete#240]
### CLI Tool
Add auto completions to volta

### Useful Links
https://docs.volta.sh/reference/

### Top Workflows
What are the most used commands or workflows in that CLI tool (for you)?

`volta fetch`
`volta install`
`volta uninstall`
`volta pin`
`volta list`
`volta which`
`volta setup`
`volta run`

**Comment by Monkeyank** [comment]
Got this one!
