### ISSUE TITLE
Bad interaction with screen

### ISSUE THREAD

**Issue by ghuh** [withfig/autocomplete#242]
### Completion Spec
The problem is with fig itself.  I could reproduce this with a number of commands.

### Description
If you type out a command completely (e.g. `git push`) such that the red > is present in the fig autocomplete.  If you hit enter I expect it to run the command.  This is true in the Terminal (stock MacOS Terminal) without screen, but if you do the same inside a screen session you have to hit enter 3 times to get it to take.  After the second enter, "New Screen..." pops up in the status bar.

This problem is specific to the version of screen shipped with MacOS.  If I try installing the latest version with brew (Screen version 4.08.00 (GNU) 05-Feb-20), then fig doesn't work at all.

### Steps to reproduce
Open a screen sessions, type `git push`, hit enter.

### Expected result
`git push` should run

### Actual result
It doesn't

### System Information
_Fig Version:_ 1.0.42

_OS:_ MacOS 10.15.7

_Device:_ MacBook Pro (Retina, 15-inch, Late 2013)

Screen version 4.00.03 (FAU) 23-Oct-06

**Comment by falky97** [comment]
Yep! A bunch of users have pointed this out recently. We currently have no support for `screen` but are going to try and fix this asap. Hopefully in the next build (v1.0.43)

Thanks for reporting.

Brendan

**Comment by SeparateRecords** [comment]
Screen isn't supported so closing as out of scope, but there's some instructions in https://github.com/withfig/fig in the zellij issue about how you can force it to work. This shouldn't be an issue anymore!
