### ISSUE TITLE
`sudo <cmd>` should show autocomplete for <cmd>

### ISSUE THREAD

**Issue by dash-awake** [withfig/autocomplete#243]
### Completion Spec
sudo

### Description
for commands that take other commands in arguments, the completion suggests options for the original command, not the one that accepts the argument.

### Steps to reproduce
run `$ sudo su -`

### Expected result
either the options for `su` such as `-l` or no completion options.

### Actual result
Fig shows `-g` in the pop-up. 

![](https://user-images.githubusercontent.com/35353302/119924821-24638b80-bf29-11eb-95d8-2721f6a7bf89.png)

### System Information
_Fig Version:_ 1.0.42

_OS:_ OSX 11.4

_Device:_ MacBook Pro

### Potential Solution
(optional) What could be a solution to solve this bug?

**Comment by CastaChick** [comment]
The bug occurs when the spec file for the entered command does not exits.
For example, when `ls` is entered after `sudo`, the completion suggestion is correctly shown.

**Comment by cstrnt** [comment]
I agree here, so I think this is rather just a missing spec than an actual bug! @dash-awake do you agree that we can close this issue?

**Comment by dash-awake** [comment]
Ideally, the completer should recognize that `su` doesn't have any spec and not prompt for `sudo`'s options. IMO, prompting command-x's options when it should prompt for command-y is a bug. Without a spec, it should not prompt anything rather than wrong options.

Without this fix, one has to keep hitting escape every time this command combination is used - which is against the goal of an auto-complete program.

Please feel free to close this as a bug, if this is out of scope or requires a lot of work. The tool is very helpful regardless.

**Comment by mattschrage** [comment]
This makes sense to me! We'll keep this open.

**Comment by SeparateRecords** [comment]
This is implemented now 🙂
