### ISSUE TITLE
`compose` is not suggested with `docker` 20.10.6

### ISSUE THREAD

**Issue by deathemperor** [withfig/autocomplete#245]
![image](https://user-images.githubusercontent.com/4255482/120172649-778d5500-c22d-11eb-82f8-12ff9db1fb48.png)

**Comment by cstrnt** [comment]
Hey there @deathemperor :)

thank you very much for creating this issue :blush:!
Would you like to fix it as well? It should be a small fix and knowing docker itself makes it quite easy :)

**Comment by Patil2099** [comment]
I would love to help in solving this issue. Can you guide me a little here @cstrnt?

**Comment by cstrnt** [comment]
@Patil2099 of course :)
Probably the best resources to get started are the following:
- https://fig.io/docs/tutorials/contributing-to-public-specs
- https://fig.io/docs/concepts/cli-skeleton

**Comment by Nutlope** [comment]
This seems like a good first issue and would love to submit a PR as a first time contributor. @Patil2099 just wanted to check if you're still interested in working on this since I don't want to steal it away from you if you are :)

**Comment by Nutlope** [comment]
#273 addresses this issue

**Comment by QuiiBz** [comment]
Merged in #273, thanks everyone!
