### ISSUE TITLE
"fig: command not found" when running `npm run dev`

### ISSUE THREAD

**Issue by zmz125** [withfig/autocomplete#246]
Welcome to Fig Dev Mode

1. Edit your spec(s) in the dev/ directory
1. On save, they will compile to the local specs/ directory
1. Test your changes instantly in your terminal
1. When done, hit ctrl + c to exit

scripts/dev.sh: line 29: fig: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! linter@1.0.0 dev: `"$npm_execpath" run build && source scripts/dev.sh`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the linter@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zmz/.npm/_logs/2021-06-01T05_43_43_983Z-debug.log

**Comment by cstrnt** [comment]
Hey there @zmz125!
What shell / OS do you use?

**Comment by zmz125** [comment]
Thank you for your reply！
Mac OS Big Sur，11.4，Terminal

**Comment by cstrnt** [comment]
You're welcome! Have you installed Fig itself yet? The `dev` script runs a `fig` command and thus fails because it cant find it!

**Comment by mattschrage** [comment]
Opened #247 to provide better error message when Fig isn't installed.

**Comment by zmz125** [comment]
Sorry, it's my problem. I didn't understand it at first, and Fig was indeed not installed. Now I installed it through Discord. 
There is another question. I just install it and use it directly, don't I need to run these commands?

**Comment by cstrnt** [comment]
This repo is not necessary to make Fig work. You can just install Fig and type something in on of our supported terminals and the autocomplete window should show up without any configuration!

**Comment by 47oo** [comment]
Fig now is beta ,I can not find it to download, and fig.io can not visit!

**Comment by zmz125** [comment]
> Fig now is beta ,I can not find it to download, and fig.io can not visit!

I download in community : Discord.
You can download in this : https://fig.io/invite?code=fig_community

**Comment by 47oo** [comment]
> > Fig now is beta ,I can not find it to download, and fig.io can not visit!
> 
> I download in community : Discord.
> You can download in this : https://fig.io/invite?code=fig_community
Thanks ,I know why I can't visit it because of our internet!

**Comment by zmz125** [comment]
哈哈，那你需要科学上网

**Comment by zmz125** [comment]
> > > Fig now is beta ,I can not find it to download, and fig.io can not visit!
> 
> > 
> 
> > I download in community : Discord.
> 
> > You can download in this : https://fig.io/invite?code=fig_community
> 
> Thanks ,I know why I can't visit it because of our internet!
> 
> 

哈哈，那你这需要科学上网

**Comment by jeff-hykin** [comment]
So does this mean there isn't a way to build fig from source? I guess I might be misunderstanding what this repo is

**Comment by fedeci** [comment]
Fig is made of several parts and not all of them are open source. 
This repo contains all the files used to provide suggestions on the terminal when you type the command. They are schemas and there is little logic behind these.

Closing this issue as it has been addressed in `autocomplete-tools` recently.

**Comment by jeff-hykin** [comment]
@fedeci Yup! Thank you

**Comment by fedeci** [comment]
Well the github logo does only mean we are linking a repo related to fig :)
