### ISSUE TITLE
[ssh] Autocomplete host for `user@hostname` ssh format

### ISSUE THREAD

**Issue by bconnorwhite** [withfig/autocomplete#249]
### Completion Spec
`ssh`

### Description
Hosts are autocompleted for `ssh [hostname]`, but not for `ssh [user]@[hostname]`.  Once you type `@`, the hosts autocomplete should return

**Comment by falky97** [comment]
Yes - this makes a lot of sense. Good suggestion. Will get someone to work on this. For anyone reading this, this will require

`filterTerm:"@"` and `trigger: "@"`

in the ssh arg and generator respectively and I believe it will work... However, you will need to do some more testing to ensure that this is correct.

**Comment by zp4rker** [comment]
Didn't realise there was an issue for this, it's been implemented by https://github.com/withfig/autocomplete/pull/689
