### ISSUE TITLE
Autocomplete requires double confirmation for `docker`

### ISSUE THREAD

**Issue by bconnorwhite** [withfig/autocomplete#250]
### Completion Spec

`docker`

### Description

Autocomplete requires double confirmation for `docker`

### Steps to reproduce

Type `docker ps` or any other docker command such that your command matches an autocomplete prompt

### Expected result

If I hit enter and what I have typed matches the autocomplete prompt exactly, it should just run rather than having to confirm twice

### Actual result

If I type `docker ps` and hit enter, the autocomplete prompt goes away and `docker ps` is not run until I hit enter a second time

### System Information

_Fig Version:_ 1.0.42

_OS:_ macOS

_Device:_ iMac

**Comment by mattschrage** [comment]
Thanks for reporting this! If you run `fig update` and pull the most recent specs, this issue should be resolved! 🎉
