### ISSUE TITLE
./scripts/create-example.sh: line 74: open: command not found

### ISSUE THREAD

**Issue by tohidplus** [withfig/autocomplete#254]
I followed the steps in the documentation one by one. But when I run the command `npm run create-example` and give it the name `abc`, I get the error below:

```bash
Successfully created the new Spec abc!

Start editing it at dev/abc.ts... We're opening it for you now!

./scripts/create-example.sh: line 74: open: command not found
npm ERR! code 127
npm ERR! path /home/myname/fig-autocomplete
npm ERR! command failed
npm ERR! command sh -c ./scripts/create-example.sh

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/myname/.npm/_logs/2021-06-03T15_43_09_533Z-debug.log

```
My OS is ubuntu 20.04.2 LTS

**Comment by mattschrage** [comment]
It seems like the `open` command does not exist on linux. 

As a heads up, the bigger issues you'll run into when developer completion specs is that currently Fig only supports macOS.
