### ISSUE TITLE
[bazel] Bazel support

### ISSUE THREAD

**Issue by rolandtshen** [withfig/autocomplete#255]
### CLI Tool
Bazel

### Useful Links
https://docs.bazel.build/versions/4.1.0/guide.html
https://github.com/bazelbuild/bazel

### Top Workflows
bazel run (target)
bazel test (target)
bazel build (target)

Having Fig autosuggest the targets based on BUILD.bazel files (similar to makefiles and how Fig is suggesting make targets rn) would be a massive plus

**Comment by QuiiBz** [comment]
Merged in #355, thanks to everyone!
