### ISSUE TITLE
I'm getting "command not found" error

### ISSUE THREAD

**Issue by jeelpatel1612** [withfig/autocomplete#267]
### Completion Spec

What completion spec does this bug refer to? Or is it Fig itself?
Ans : Fig itself

### Description

Describe the issue that you're seeing.
Ans : i followed "[getting started](https://fig.io/docs/getting-started)" guide on fig.io website and when i run `npm run dev`.
That gives me following error...
```
Welcome to Fig Dev Mode

1. Edit your spec(s) in the dev/ directory
2. On save, they will compile to the local specs/ directory
3. Test your changes instantly in your terminal
4. When done, hit ctrl + c to exit

scripts/dev.sh: line 29: fig: command not found
```

### Steps to reproduce

Clear steps describing how to reproduce the issue. **Please** link to a reproduction, this makes your issue _much_ easier to diagnose (seriously).
Ans : I followed "[getting started](https://fig.io/docs/getting-started)".

### Expected result

What should happen?
Ans : As per the DOCs, it should start the dev program script and i should see it's functionality of command suggestions.

### Actual result

What happened.
Ans : i got error and command suggestions were not showing.

### System Information

_Fig Version:_
Ans : i don't know the version number but i used latest repo from GitHub on "Sunday, 6 June 2021
Coordinated Universal Time (UTC)"

_OS:_
Ans : macos big sur v11.2

_Device:_
Ans : macbook air m1

### Potential Solution

(optional) What could be a solution to solve this bug?

**Comment by cstrnt** [comment]
Hey there @jeelpatel1612,
it seems like you haven't downloaded Fig itself yet!
This repo only contains the completions specs for the main Fig; think of it like a DLC for the App itself :)
You can download the App [here](https://fig.io/).

P.S. Joining our [Discord](https://fig.io/community) gives you access faster ;)

**Comment by jeelpatel1612** [comment]
Oh, Ok. I'll do it. Thanks for the help. Anyway, please mention this in DOCs if it isn't?

**Comment by yangjunPrivate** [comment]
can you tell how to download fig? i have the same problem

**Comment by yangjunPrivate** [comment]
thanks
