### ISSUE TITLE
Make it possible to increase the default generator timeout

### ISSUE THREAD

**Issue by nagypeterjob** [withfig/autocomplete#270]
### Completion Spec
What completion spec does this enhancement refer to? Or is it Fig itself?
Each long-running generators

### Description
Describe the issue that you're seeing.

### Steps to reproduce
Create any long running generator & see it fail after 5 seconds

### Expected result
What should happen?

There are generators that create long-running request. It would be nice to have a way to set this timeout for a given generator.

### Actual result
What happened.

**Comment by SeparateRecords** [comment]
This is fixed now! Generators can individually specify a timeout in ms. IMO the default timeout is sane and should be kept as is, long-running generators should have their timeout increased individually.
