### ISSUE TITLE
[yarn] Yarn workspace support

### ISSUE THREAD

**Issue by davidfant** [withfig/autocomplete#274]
### Completion Spec
yarn workspace

### Description
There is no autocomplete for `yarn workspace`. It's expected to run scripts within specific workspaces

`https://yarnpkg.com/cli/workspace`

### Steps to reproduce
package.json

```json
{
  "workspaces": ["subdirectory"]
}
```

subdirectory/package.json

```json
{
  "name": "subdirectory-project"
  "scripts": {
    "hello": "echo 'world'"
  }
}
```

### Expected result
Typing `yarn workspace subdirectory-project` should autocomplete `yarn workspace subdirectory-project hello`

### Actual result
No autocomplete

**Comment by Nutlope** [comment]
Working on this! Will submit a PR soon

**Comment by Nutlope** [comment]
#361 has been merged
