### ISSUE TITLE
[git] Long running git commands in Fig prevent executing commands

### ISSUE THREAD

**Issue by brendanfalk** [withfig/autocomplete#278]
In a git repo, if i type `git add[space]`, the git completion spec runs `git status --short`, parses the output, and renders each file/folder as suggestions.

When a git command is run in a specific repo, git creates an `.git/index.lock` file which prevents other git commands from running at the same time. It will output an error saying `another git process seems to be running in this repository`.

In really really big repos (monorepos at companies), a command like `git status --short` may take a while (maybe around 1 second). So, if a user types `git add .`, then presses enter quite quickly, Fig's pseuodterminal will still be waiting for the response from the `git status --short` we are running. But the user's local shell will be trying to run the `git add .` command. This will yield an annoying error for the user.

Some work arounds:

* Entirely disable git in Fig until this is fixed: `fig settings autocomplete.disableForCommands '["git"]'`
* Change the git commands in the completion spec such that they are much faster and/or don't create the index.lock file
* Kill whatever is running in pseudo terminal in preexec hook

**Comment by fwesss** [comment]
Fixed with https://github.com/withfig/autocomplete/pull/410
