### ISSUE TITLE
When typing with "./", the autocomplete window flashes

### ISSUE THREAD

**Issue by Monkeyank** [withfig/autocomplete#291]
### Completion Spec
What completion spec does this bug refer to? Or is it Fig itself?
Dotslash

### Description
Typing after "./", the autocomplete window flashes, but when you type dotslash and start typing a filepath/folder the autocomplete window **doesn't** flash.

### Steps to reproduce
https://user-images.githubusercontent.com/40261054/121772139-74953d00-cb28-11eb-954f-7adb2002fab0.mov

### Expected result
What should happen?

### Actual result
What happened.

### System Information
_Fig Version:_ 1.0.43

_OS:_ MacOS 11.0.1 (Big Sur)

_Device:_ Macbook Pro Early 2015

### Potential Solution
(optional) What could be a solution to solve this bug?

**Comment by brendanfalk** [comment]
Yes, this is annoying. Have noticed this too. An issue with our optimization function I believe. Will try and fix early next week

**Comment by Monkeyank** [comment]
@mschrage This has been fixed, right?
