### ISSUE TITLE
[Django] CLI Request

### ISSUE THREAD

**Issue by Monkeyank** [withfig/autocomplete#298]
### CLI Tool
Django (`django-admin` and `python3 manage.py`)

### Useful Links
[https://docs.djangoproject.com/en/3.2/ref/django-admin/](https://docs.djangoproject.com/en/3.2/ref/django-admin/)

**Comment by wilhelmklopp** [comment]
I've started working on this and have been making a little bit of progress, but hitting a lot of snags along the road, mainly to do with python virtual environments. More context in [#dev-help](https://discord.com/channels/837809111248535583/839904703214649345)

I'm trying to use the existing tooling Django provides around CLI info and use that to populate the spec, so I'm making a lot of use of fig's `generateSpec`. I think that approach will make this spec future-proof even when Django decides to add more subcommands, options, and arguments. It also has the benefit of providing completion info for user-specified management commands

![image](https://user-images.githubusercontent.com/7718702/123427500-9c6eb100-d5bc-11eb-961d-d5bf53c04648.png)
