### ISSUE TITLE
Find a way to share code across completion specs

### ISSUE THREAD

**Issue by QuiiBz** [withfig/autocomplete#302]
**Is your feature request related to a problem? Please describe.**
Based on https://github.com/withfig/autocomplete/pull/288, the `yarn` and `npx` specs should share the same CLIs (e.g `yarn electron` and `npx electron`. Currently,  this would lead to duplication and is not very handy.

**Describe the solution you'd like**
Having a way to share code like generators, arguments, and more across many completion specs would be really cool. The exact implementation will need to be discussed here.

**Comment by fedeci** [comment]
We may add an `eslint` plugin to enforce naming of the completion spec esport. 
For example `eslint` is doing that internally for their rules. I can work on that if needed.

**Comment by QuiiBz** [comment]
@cstrnt has been working on this in #388 - this is going to be amazing!

**Comment by Monkeyank** [comment]
Closed with #388
