### ISSUE TITLE
[rails] Spec does not work on macOS mojave

### ISSUE THREAD

**Issue by brendanfalk** [withfig/autocomplete#320]
When your current working directory is a rails app and you are on macOS mojave, suggestions do not show up. 

Why? 

The `rails` completion spec uses the `matchAll` function. This is a new function in javascript land and is not valid in older versions of safari (Fig uses a wkwebview under the hood and both use webkit). 

To fix:

Replace .matchAll with .exec or .match and do a loop. This article compares the three: https://www.tsmean.com/articles/regex/javascript-regex-match-vs-exec-vs-matchall/

**Comment by mattschrage** [comment]
Should we just add a polyfill for this in the autocomplete app? What do you think @cstrnt @QuiiBz  @sullivan-sean?

**Comment by sullivan-sean** [comment]
I can imagine this being useful in other places as well so I think polyfilling makes the most sense here. Would also be very easy to do a `.match` loop

**Comment by fedeci** [comment]
Maybe polyfill just for Safari 14 since 13 is outdated.

**Comment by QuiiBz** [comment]
> To avoid having to import single polyfills, I'd propose to start using Babel instead of TS bot for transformation and polyfill injection, and keeping TS just to check types.

The current TS compiler has special features - it transpile TS to JS, then rename the exported spec and remove the export keyword.

Making a polyfill would be a lot faster (and also easier) in this case.

**Comment by fedeci** [comment]
Yes, I know, nothing that Babel could not do however. As already mentioned in a previous issue in my opinion it would be better to ensure through eslint that every file has a `completionSpec` export.

**Comment by SeparateRecords** [comment]
Pretty sure this is done now but will reopen if I'm wrong
