### ISSUE TITLE
Custom specs overwrite existing spec files

### ISSUE THREAD

**Issue by petergoes** [withfig/autocomplete#328]
### Completion Spec

What completion spec does this bug refer to? Or is it Fig itself?
Fig itself

### Description

In Git, you can create your own subcommands (http://thediscoblog.com/blog/2014/03/29/custom-git-commands-in-3-steps/). To get autocompletions for that subcommand in fig, you'll create a spec file which you then copy using `npm run copy git`. This process replaces the existing `git.js` file in `~/.fig/autocomplete/git.js`. Making all git autocomplete options disappear

### Steps to reproduce

1. Follow tutorial 'Create visual shortcut & aliases' (https://fig.io/docs/tutorials/visual-shortcuts)
2. Rename spec file from `dev/+.ts` to `dev/git.ts`
3. Update `dev/git.ts` to contain:
```js
export const completion: Fig.Spec = {
  name: "git",
  subcommands: [
    {
      name: 'pull-on',
      args: {
        name: 'branch',
        generators: {
          script: "git branch | awk '{ print $1$2 }'",
          postProcess: function(out) {
            return out.split('\n').map(branch => {
              const branchName = branch.replace(/^\*/, '')
              return { name: branchName, description: `Branch ${branchName}`, icon: '⬇️'}
            })
          }
        }
      }
    },
  ]
}
```
4. execute `npm run build`
5. execute `npm run copy git`
6. In a terminal type `git [space]`
7. Inspect `~/.fig/autocomplete/git.js`
8. See that the file only contains the locally written code, all other code is missing

### Expected result

All git sub commands should be listed in addition to `git pull-on`

### Actual result

Only `git pull-on` is available together with any custom git aliases

### System Information

_Fig Version:_ 1.0.45 (B218)

_OS:_ macOS 11.4

_Device:_ Maxbook Pro

### Potential Solution

(optional) What could be a solution to solve this bug?

When copying a local spec file, it should be merged with original spec files

**Comment by brendanfalk** [comment]
Yes. completely agree with this. This is super annoying. I think the optimal way to fix this is actually making it easy to add custom suggestions to any level of a CLI tool that get auto-merged in.

For instance, you may want to add custom suggestions to `git checkout` or `ssh`. I think we will create a file where you can create custom suggestions for each CLI tool and they will get merged at runtime.

Good catch, thanks for reporting

**Comment by petergoes** [comment]
It sounds like 'fixing it during runtime' would be the optimal solution. Now the copy command copies the custom specs into all default specs. I for see other issues where people have created a spec for themselves, with an update an 'official' spec is pulled which overwrites the custom one. That would lead to some hard to debug issues I guess.

So copy might move custom specs to `~/.fig/autocomplete.local`? Separating custom from standard specs seems like a good idea.

**Comment by SeparateRecords** [comment]
Resolved now! You can either create a mixin in the `fig` UI or create a spec for `git-[commandname]` which should be loaded by the git spec
