### ISSUE TITLE
Provide better support for viewing suggestion descriptions

### ISSUE THREAD

**Issue by brendanfalk** [withfig/autocomplete#333]
### Aim
Make it ridiculously easy and simple to view descriptions about a given suggestion
**More specifics**: 
* Fully keyboard accessible 
* Don't require users to memorise any keyboard shortcuts - should be able to get anywhere from the UI
* Don't make the app jumpy or flash - have smooth transitions
* Make sure we use a hotkey that doesn't override any existing terminal / IDE hotkey

### Proposed Solution
Have a keyboard shortcut that adds a mini popover within the autocomplete window which has the full description. A hotkey should show and hide it

My shitty mockups macOS preview (could've made this beautiful in Figma, but implementation and usability is more important issue first. We will obviously make it look nice and sleek).

Figure 1: Normal state. If the user clicks `cmd+i` it will open up description state

![image](https://user-images.githubusercontent.com/4949076/123706184-cde5b780-d81c-11eb-936b-19f1b0a828ee.png)

Figure 2: Description state. 

- If user clicks `cmd+i` it will revert back to normal state. The description box should have max height of 120px. Any more text should scroll
- The description box should take up the full autocomplete window screen
- Clicking the up and down and down arrows should overflow with vertical scroll
- The background colour should fit in with the colour scheme. Perhaps a light grey?

![image](https://user-images.githubusercontent.com/4949076/123706213-d63df280-d81c-11eb-9087-4cdff3a1d024.png)

**Other notes**

If there is only one suggestion in normal state and the user hits `cmd+i`, we should still expand the description box to fit all the text

e.g. if the user hit `cmd+i` here it should still expand to be the same as Figure 2, capped at max height 120px

![image](https://user-images.githubusercontent.com/4949076/123706229-db9b3d00-d81c-11eb-8b54-49f5e52c7428.png)

### Cool things for the future
Why should this description box be limited to just simple descriptions. Why can't we provide more info about a specific suggestion type. e.g give much more info about files and folder, give commit history for a given git branch etc

**Examples**

![image](https://user-images.githubusercontent.com/4949076/123706236-df2ec400-d81c-11eb-8ff0-388a051b7673.png)

![image](https://user-images.githubusercontent.com/4949076/123706262-e655d200-d81c-11eb-9f7d-b2d1132cf96a.png)

Please comment thoughts + other ideas below!

**Comment by QuiiBz** [comment]
A more descriptive box seems like a good idea, but I feel like it's a bit strange to hide the whole autocomplete suggestions.

I came up with this idea (badly designed sorry) which is more like VSCode's types/doc box:
<img width="530" alt="Screenshot 2021-06-29 at 08 42 28" src="https://user-images.githubusercontent.com/43268759/123750109-801d8d80-d8b6-11eb-8fb3-75886b3ceb7b.png">

This can sit at the right (or left if not enough spaces) so it won't hide the suggestions.

**Comment by brendanfalk** [comment]
@QuiiBz Yes I agree, the way VSCode has built this is very nice and would likely be better. It is quite hard for us to build an entirely new box and position it accordingly, however, there is no reason why this couldn't be baked into the existing window and we have some delimiter... Will discuss with @mattschrage tomorrow.

We want to make this fully keyboard accessible. I imagine when you have the description box open, you would want to use arrow keys to navigate up and down the description. Would this still make sense? I guess we could also do shift+arrow key to navigate the description and then normal arrow key to navigate the suggestions... Could work quite nicely. I like it

And don't worry, your drawing couldn't be worse than mine haha

**Comment by QuiiBz** [comment]
Exactly, there is no need to summon a new fig window, it can simply be embedded into the same. 

I agree with the `Shift+Arrow` shortcuts, along with normal mouse/trackpad scrolling. There also can be another shortcut to show/hide this information box. VSCode does this with `Command+Space`, which I find pretty handy.

**Comment by brendanfalk** [comment]
Concern is when there is only one suggestion what we do...

We would have to expand the box from this:
![image](https://user-images.githubusercontent.com/4949076/123842117-4738e500-d8c5-11eb-9159-a1413e08bae7.png)


To this
![image](https://user-images.githubusercontent.com/4949076/123842151-5029b680-d8c5-11eb-98b9-870a306048a6.png)

**Comment by fedeci** [comment]
Can’t we provide a sort of Master-Detail approach, where the master is not upscaled in that case? Maybe it would be a bit strange(?)

**Comment by mattschrage** [comment]
@fedeci the current constraint we're operating under is that the description text needs to be contained in a single NSWindow/WKWebview. 

Right now we can't easily make parts of the view transparent, but this is something @Monkeyank is looking into.

**Comment by fedeci** [comment]
Happy to give you a hand if needed!
