### ISSUE TITLE
[git] suggest staged unstaged files as argument for `git diff`

### ISSUE THREAD

**Issue by mschrage** [withfig/autocomplete#374]
<img width="370" alt="Screen Shot 2021-07-14 at 3 50 48 PM" src="https://user-images.githubusercontent.com/3155109/125702799-cadb2cad-2131-4ab0-af4c-b3ce44d4f9fd.png">

Having files in addition to commits would be really useful!

**Comment by QuiiBz** [comment]
Merged in #386!
