### ISSUE TITLE
Errors From Generators Displayed As Suggestions

### ISSUE THREAD

**Issue by ankithm28** [withfig/autocomplete#375]
### Description

If you run a script inside a generator and that command is not found, then the error is displayed as a suggestion.

### Steps to reproduce

Go to a spec that you don't have locally installed. Go to a subcommand that has a generator. For example, I don't have `go` installed, so I tried `go tool`.
<img width="296" alt="Screen Shot 2021-07-14 at 4 08 52 PM" src="https://user-images.githubusercontent.com/40261054/125704149-d00ca48c-abcc-434c-9d79-afde9c68aea4.png">

### System Information

_Fig Version:_ 1.0.45

_OS:_ macOS Big Sur

_Device:_ mbp Pro

### Potential Solution

If you run a script and that command is not found, then the engine should handle that. It shouldn't output an error message as a suggestion.

**Comment by mattschrage** [comment]
Yeah, this has always been a little bit strange. I think that having some indication why a generator failed can be useful but it shouldn't be selectable/insertable.

**Comment by acedward** [comment]
Same here, gets unusable - e.g., `cat ` always tries to complete with an error. 

![image](https://user-images.githubusercontent.com/3951895/136020873-bb64c8ab-6aa2-4f36-b7cc-72498fb7bfdf.png)
