### ISSUE TITLE
[git] Prioritize unstaged files for `git add`

### ISSUE THREAD

**Issue by mschrage** [withfig/autocomplete#376]
<img width="807" alt="Screen Shot 2021-07-14 at 4 21 02 PM" src="https://user-images.githubusercontent.com/3155109/125705264-6b20de70-70cf-4594-8261-7e33129b2f8d.png">

For example, `tools/drip/prompt_to_update.sh` should be the top suggestion. 

Another solution: files that have already been staged could be removed from the list of suggestions?

**Comment by dereklowlind** [comment]
@mschrage  please check out the PR I did for this!

**Comment by QuiiBz** [comment]
Merged in #380, thanks everyone!
