### ISSUE TITLE
support for jetbrains terminal

### ISSUE THREAD

**Issue by koesper** [withfig/autocomplete#38]
I know that the various integrations are still a work in progress, but is integration with jetbrains' terminal (IntelliJ / PHPstorm / Rider / ...) somewhere on the roadmap?

**Comment by falky97** [comment]
Hopefully going to get it working soon! We have an issue open for this in our main repo (https://github.com/withfig/fig/issues/25). Feel free to subscribe to it for a ping when it's ready! I am going to close this for now :)
