### ISSUE TITLE
[npm] Npm uninstall should be able to take more than 1 arg

### ISSUE THREAD

**Issue by Nutlope** [withfig/autocomplete#391]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue

### What CLI tool does this relate to?

npm

### Which statement makes the most sense?

There is a bug with this completion spec

### Issue Details

Npm uninstall only allows 1 argument, but the user should be able to input many args to uninstall various packages at the same time.

**Comment by Nutlope** [comment]
Working on this

**Comment by Monkeyank** [comment]
Closed with #392
