### ISSUE TITLE
[composer] not working

### ISSUE THREAD

**Issue by JannieT** [withfig/autocomplete#415]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue

### What CLI tool does this relate to?

composer

### Which statement makes the most sense?

There is a bug with this completion spec

### Issue Details

After my last FIG update, I can see a file called `~/.fig/autocomplete/composer.js`, but when I type `composer` + SPACE there are no FIG autocomplete options like I expected.

FIG v1.0.46 restarted FIG and all terminal sessions.

**Comment by Monkeyank** [comment]
@JannieT Would you mind running and sending the output of `composer list --format=json`?

**Comment by olivM** [comment]
here is mine : 
[composer-list.json.txt](https://github.com/withfig/autocomplete/files/6922186/composer-list.json.txt)

**Comment by JannieT** [comment]
Composer auto-completion has now started to work. I have rebooted my macbook since I last tried, so that must have been it. Sorry for the false alarm.
