### ISSUE TITLE
Add installation guide to README.md such that exposing email is optional

### ISSUE THREAD

**Issue by TimDaub** [withfig/autocomplete#42]
When looking at the GitHub repo of this project, it's unclear how to install the tool.
Please add a section about installing without requiring the user's email, thanks.

**Comment by falky97** [comment]
Hey Tim - We are currently in private beta, hence why there is no direct install link. When we open it up, we will let you install through brew!

We will likely have an option to sign in as a guest too. There reason we ask for email is to make it easy to share scripts, profiles, etc across your team :)

Closing for now, but feel free to re-open if I'm missing something

**Comment by falky97** [comment]
btw your personal website is awesome
