### ISSUE TITLE
[YARN] Load specs of cli that exists in current package is not working

### ISSUE THREAD

**Issue by EliasGcf** [withfig/autocomplete#420]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue

### What CLI tool does this relate to?

yarn

### Which statement makes the most sense?

There is a bug with this completion spec

### Issue Details

According to this PR #167, when I use `yarn next` should show a completion, but is not working.

![image](https://user-images.githubusercontent.com/50633599/127582779-aa75ca8b-7c42-40c4-a0a1-7265dd3d5c51.png)

![image](https://user-images.githubusercontent.com/50633599/127582807-ac978f97-7406-4683-b9cc-97dcb1a1a6d0.png)

**Comment by QuiiBz** [comment]
Thanks for reporting this issue. Looks like it's due to our internal autocomplete engine, not the yarn spec itself. We are going to invest in this and keep this issue updated.

**Comment by EliasGcf** [comment]
Hi, @QuiiBz, I think this issue can be closed.

I test the case again and it is working.

![image](https://user-images.githubusercontent.com/50633599/129811924-e48505d4-83c6-4266-b39f-c530d0b2e17b.png)

![image](https://user-images.githubusercontent.com/50633599/129811959-e5ee2f95-e97f-4cd8-b800-ecd53b41fe0b.png)

Thank you for the attention.

**Comment by QuiiBz** [comment]
It has been fixed in the internal engine. Thanks for your help!
