### ISSUE TITLE
Switch to TypeScript?

### ISSUE THREAD

**Issue by QuiiBz** [withfig/autocomplete#43]
Hi,

I think that the autocomplete specs are really powerful and customizable. But writing them in plain JS is pain without auto-completion from IDEs. Do you plan to switch to `TypeScript` in the future?

I really think that it could help a lot of peoples to contribute to new autocomplete specs.

**Comment by falky97** [comment]
Agree - we aren't typescript gods, would you be open to helping with this? 

We set up schema validation with https://joi.dev/ but obviously assistance when you are coding would be better

**Comment by QuiiBz** [comment]
Sounds good - I will open a PR tomorrow.

**Comment by falky97** [comment]
You're awesome, thank you so much. Everything here should be up to date: https://withfig.com/docs/autocomplete/api

**Comment by QuiiBz** [comment]
Closing issue since we merged it in #44.
