### ISSUE TITLE
php artisan auto-complete buggy delay

### ISSUE THREAD

**Issue by eckelarsson** [withfig/autocomplete#434]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue

### What CLI tool does this relate to?

artisan

### Which statement makes the most sense?

There are errors with this completion spec

### Issue Details

The auto-complete won't show upp unless i write php artisan, then hit space and then wait 1s - 5s for the dialog of suggestion comes up. If you write it fast you won't get any auto-complete.

Hardware: Macbook Pro 16 gb M1
OS Version: 11.4
Terminal: iTerm2 - zsh - Oh my Z

**Comment by apithy-isidro-martinez** [comment]
same here, the dialog don't shows up when i hit `php artisan`

**Comment by SeparateRecords** [comment]
Should be resolved now!
