### ISSUE TITLE
Update lockfile

### ISSUE THREAD

**Issue by Nutlope** [withfig/autocomplete#454]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue

### What CLI tool does this relate to?

NA

### Which statement makes the most sense?

Something else

### Issue Details

Lockfile needs to be updated

![image](https://user-images.githubusercontent.com/63742054/128795332-8b2c1dbf-1240-404c-86f0-318d15f42143.png)

**Comment by Monkeyank** [comment]
I think this has been fixed with the npm ci #463. Reopen if needed!
