### ISSUE TITLE
git worktree

### ISSUE THREAD

**Issue by cameroncooke** [withfig/autocomplete#469]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue

### What CLI tool does this relate to?

git

### Which statement makes the most sense?

This completion spec isn't complete

### Issue Details

Could we add support `git worktree` auto-completion?

This allows you to have multiple "worktrees" allowing you to check out multiple branches at the same time.

A use-case is you're working in a specific branch, but quickly need to check or work in another branch and don't want to have to stash or commit your changes, switch branches and then do the reverse when you're finished. You could clone the repo multiple times but they are hard to keep in sync. Worktrees don't consume any extra disk space for each branch checked out.

Basic use is via the `add`, `remove` and `list` options.

Add a worktree for `main` branch:

```bash
$ git worktree add ~/Developer/SomeNewDirectory main
```

Remove the `main` worktree:

```bash
$ git worktree remove ~/Developer/SomeNewDirectory
```

List worktrees:

```bash
$ git worktree list
```

It's worth noting that `git worktree add` will create the given directory. 

From `git worktree --help`
```
       git-worktree - Manage multiple working trees

       git worktree add [-f] [--detach] [--checkout] [--lock] [-b <new-branch>] <path> [<commit-ish>]
       git worktree list [--porcelain]
       git worktree lock [--reason <string>] <worktree>
       git worktree move <worktree> <new-path>
       git worktree prune [-n] [-v] [--expire <expire>]
       git worktree remove [-f] <worktree>
       git worktree repair [<path>...]
       git worktree unlock <worktree>
```

**Comment by jackneer** [comment]
@brendanfalk @Monkeyank I'd like to give it a try. please assign thanks!

**Comment by davidalpert** [comment]
this one appears to have been added in October of last year by #675

**Comment by SeparateRecords** [comment]
Thank you @davidalpert! Closing this issue
