### ISSUE TITLE
autocomplete area is showing on other screen

### ISSUE THREAD

**Issue by berkbaski** [withfig/autocomplete#48]
autocomplete panel is showing (I THINK) on first screen when using on other screen and full size mode. Not happening when terminal size is normal mode.

# FULL SIZE
![Screen Shot 2021-03-14 at 17 31 42](https://user-images.githubusercontent.com/25839586/111072442-b0017a80-84eb-11eb-97b3-f29f8be922cb.png)

<hr/>

# NORMAL SIZE
![Screen Shot 2021-03-14 at 17 31 32](https://user-images.githubusercontent.com/25839586/111072444-b263d480-84eb-11eb-9ecb-48222874194c.png)

**Comment by falky97** [comment]
Thanks for reporting. Yes - aware of this issue. We had some issue testing this with our current monitor. We are getting a new one and will hopefully have this fixed in < 2 weeks now!

Brendan Falk
Co-founder & CEO @ Fig
***@***.***
(857) 800-1383

**Comment by mattschrage** [comment]
This should be fixed in build v1.0.40. 🎉
