### ISSUE TITLE
[Windows support]

### ISSUE THREAD

**Issue by rukundob451** [withfig/autocomplete#480]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue

### What CLI tool does this relate to?

How can I be able to get it on windows?

### Which statement makes the most sense?

Something else

### Issue Details

I was trying to use it for windows but wasn't able to.

**Comment by Monkeyank** [comment]
Fig currently works on macOS only. The Fig team will build a port that integrates with Windows soon.
Please subscribe to this issue to get an update when Fig's autocomplete integration with the Window is ready 😄

Closing in favor of: https://github.com/withfig/fig/issues/35

Feel free to still  build completion specs if you'd like!
