### ISSUE TITLE
`yarn workspace [name of workspace]` suggests directory names instead of workspace name

### ISSUE THREAD

**Issue by emilio-martinez** [withfig/autocomplete#483]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue

### What CLI tool does this relate to?

yarn

### Which statement makes the most sense?

There is a bug with this completion spec

### Issue Details

When typing `yarn workspace [name of workspace] *`, the autocompletion suggests the name of workspace directories, but it should be suggesting the values of the `name` field of the corresponding `package.json`s. Otherwise, proceeding will result in errors such as the following:

```sh
Workspace '[name of workspace]' not found. Did you mean any of the following:
...
```

### Example reproduction

In a project directory using yarn workspaces, type `yarn workspace [name of workspace] [command in workspace]`, using autocompletion for both sections within brackets. I'm using the following configuration:

```
yarn v3.0.0
node v14.17.4
fig v1.0.47 (with updated autocompletions as of this message)
```

**Comment by fedeci** [comment]
Working on this

**Comment by QuiiBz** [comment]
Fixed in https://github.com/withfig/autocomplete/pull/678 🚀
