### ISSUE TITLE
[git] In fig, the command prompt for git is not working. 

### ISSUE THREAD

**Issue by QuentinHsu** [withfig/autocomplete#500]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [X] I would like to work on this.

### What CLI tool does this relate to?

git

### Which statement makes the most sense?

Something else

### Issue Details

In fig, the command prompt for git is not working. The command prompt for npm is working.

![image](https://user-images.githubusercontent.com/21162238/130174420-715d127f-a025-4db1-8233-fe9e1914b8cf.png)
![image](https://user-images.githubusercontent.com/21162238/130174452-3f42e3ee-ffb3-49d7-a41a-3af2050c9e53.png)

Desired：
![image](https://user-images.githubusercontent.com/21162238/130174534-fabb5299-c15a-4443-9862-dba6164fdb1e.png)

In my MacBook Pro（13-inch, M1, 2020，macOS：^11.4）：
![image](https://user-images.githubusercontent.com/21162238/130174474-79c3be50-bec3-461e-992e-490ce4c003f0.png)

In the early days after I installed fig, I was able to use the fig about git command prompt. However, in the last two months I have noticed that suddenly the above prompts are no longer displayed. Reinstalling doesn't help.

**Comment by mschrage** [comment]
What version of macOS are you using?

**Comment by QuentinHsu** [comment]
> What version of macOS are you using?

The current macOS version is: 11.5.2

**Comment by Nutlope** [comment]
@qnkhuat Do you have an alias associated with git? If you do, git autocomplete may not work. You can check by typing `which git` into your terminal.

**Comment by QuentinHsu** [comment]
> @qnkhuat Do you have an alias associated with git? If you do, git autocomplete may not work. You can check by typing `which git` into your terminal.

![image](https://user-images.githubusercontent.com/21162238/130306662-8bbcf708-6f96-4c2e-b113-1d408b9f44c3.png)

With your tip, I removed the alias about git from the ~/.zshrc file and source ~/.zshrc, and after restarting the terminal, the fig prompt about git worked again.

![image](https://user-images.githubusercontent.com/21162238/130306777-ff62c57d-c9c9-4901-b69f-77c03c7e30b0.png)

Thank you very much!
