### ISSUE TITLE
[rsync] completion spec

### ISSUE THREAD

**Issue by jonbackhaus** [withfig/autocomplete#510]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [ ] I would like to work on this.

### What CLI tool does this relate to?

rsync

### Which statement makes the most sense?

This completion spec does not exist

### Issue Details

Lots of arguments with the potential to re-use generators from SSH

**Comment by Guergeiro** [comment]
I would like to work on this! Just @ me and assign me if possible.
