### ISSUE TITLE
[aws] - Suggest AWS profiles

### ISSUE THREAD

**Issue by danilofuchs** [withfig/autocomplete#542]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [X] I would like to work on this.

### What CLI tool does this relate to?

aws

### Which statement makes the most sense?

This completion spec isn't complete

### Issue Details

All AWS commands can be suffixed with `--profile PROFILE`, in which `PROFILE` is one of the configured profile and can be fetched using `aws configure list-profiles`.

I suggest Fig autocompletes the profile list on **all** aws commands

https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

**Comment by joeheyming** [comment]
https://github.com/withfig/autocomplete/pull/1670
