### ISSUE TITLE
[npm] Autocomplete for --legacy-peer-deps not available

### ISSUE THREAD

**Issue by akashshyamdev** [withfig/autocomplete#545]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable):
Here's the autocomplete that appears when `--legacy-` is entered:
![Screenshot 2021-08-31 at 14 22 33](https://user-images.githubusercontent.com/56759828/131473033-1e19fde4-46eb-4f4e-b4a2-87ebe8ff10ba.png)

As you can see, only `--legacy-bundling` is shown and not `--legacy-peer-deps` which is a common configuration option. Is there a reason for this? 

 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.5.2|Version 1.0.47 (B257)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.47 (B257) [ABC - India] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/akash/.fig/bin/fig
Accessibility: true
Number of specs: 185
SSH Integration: false
Tmux Integration: true
Keybindings path: /Users/akash/.fig/user/keybindings
iTerm Integration: true 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /usr/local/share/npm/bin:/Users/akash/.rbenv/shims:/Users/akash/anaconda3/bin:/Users/akash/anaconda3/condabin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/akash/Library/Android/sdk/platform-tools:/usr/ucb:/usr/local/mysql/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /usr/local/Cellar/node/15.11.0/bin/node (27137) - ttys004
Current working directory: /Users/akash/Code/Projects/microfrontend
Current window identifier: 37693/code:26117% (com.microsoft.VSCode)</pre>
</p>
</details>

**Comment by QuiiBz** [comment]
Merged in #610, thanks!
