### ISSUE TITLE
[git] `HEAD` autocompletes to `HEAD~`

### ISSUE THREAD

**Issue by peterkhayes** [withfig/autocomplete#578]
### Description:
A common workflow I use is `git reset HEAD`, sometimes with `--hard`. When using Fig, `HEAD` gets autocompleted to `HEAD~`. This is potentially dangerous, as `git reset HEAD~` would reset to the commit _before_ the current head.

![image](https://user-images.githubusercontent.com/3714569/132775626-1ab3ca78-c356-4d43-8276-fd58b2929085.png)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.2.3|Version 1.0.48 (B264)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.48 (B264) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/phayes/.fig/bin/fig
Accessibility: true
Number of specs: 199
SSH Integration: false
Tmux Integration: true
Keybindings path: /Users/phayes/.fig/user/keybindings
iTerm Integration: true 
Hyper Integration: false
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: [oh-my-zsh]
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (86878) - ttys005
Current working directory: /Users/phayes/figma/figma/web
Current window identifier: 122786/% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by peterkhayes** [comment]
PR is here https://github.com/withfig/autocomplete/pull/579

**Comment by QuiiBz** [comment]
Merged in #579, thanks!
