### ISSUE TITLE
[maven] Support

### ISSUE THREAD

**Issue by fwesss** [withfig/autocomplete#605]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [ ] I would like to work on this.

### What CLI tool does this relate to?

maven

### Which statement makes the most sense?

This completion spec does not exist

### Issue Details

Maven is a build tool typically used with java.

https://maven.apache.org/ref/3.8.1/maven-embedder/cli.html

**Comment by zp4rker** [comment]
@Cool-Runningz sorry if you already started on it, but I noticed its been a while so I decided to do it 😬 

PR submitted @ https://github.com/withfig/autocomplete/pull/746
