### ISSUE TITLE
Missing script: "create-example"

### ISSUE THREAD

**Issue by Hongbo-Miao** [withfig/autocomplete#613]
When I follow [Get Started](https://github.com/withfig/autocomplete/blob/e798be751ff90eb2d1cbc67fa85c5edc8d84e97e/README.md#-get-started), this step

```sh
npm run create-example
```

gives me error

> Missing script: "create-example"

When I check package.json file, it also does not have `create-example` in scripts section

https://github.com/withfig/autocomplete/blob/e798be751ff90eb2d1cbc67fa85c5edc8d84e97e/package.json#L9-L19

**Comment by fedeci** [comment]
It has been replaced by the `create-spec` subcommand (`npm run create-spec [name of the spec]`). I will update the README!
