### ISSUE TITLE
Hi, sorry for abandoning my PR earlier. I will now continue to work on it.

### ISSUE THREAD

**Issue by mlitvin116** [withfig/autocomplete#631]
Hi, sorry for abandoning my PR earlier. I will now continue to work on it.

_Originally posted by @geenva in https://github.com/withfig/autocomplete/issues/630#issuecomment-932438523_

**Comment by geenva** [comment]
@fedeci any idea what this is?

**Comment by fedeci** [comment]
No idea, just spam I suppose.
