### ISSUE TITLE
Support GNU executables

### ISSUE THREAD

**Issue by jonbackhaus** [withfig/autocomplete#709]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [ ] I would like to work on this.

### What CLI tool does this relate to?

ls

### Which statement makes the most sense?

There is a bug with this completion spec

### Issue Details

My default `ls` options are `-alh`
Fig then recommends `-alh@` which fails on macOS
It seems like Fig should not be making this recommendation?

**Comment by mschrage** [comment]
Thanks for letting us know @jonbackhaus

**Comment by jonbackhaus** [comment]
Stupid question: is the fix as simple as removing that declaration from ls.ts? Because even I can do that!

**Comment by fedeci** [comment]
Is `-@` even a valid option for `ls`? I can't find it mentioned anywhere.

**Comment by mschrage** [comment]
<img width="559" alt="Screen Shot 2021-11-09 at 6 07 42 PM" src="https://user-images.githubusercontent.com/3155109/141036488-178870f9-10ff-4f45-83e2-2ee8f2283585.png">

**Comment by jonbackhaus** [comment]
That's interesting because it's different on my macOS (12.0.1):
<img width="1088" alt="Screen Shot 2021-11-13 at 2 16 21 PM" src="https://user-images.githubusercontent.com/10749098/141656457-bfa8967a-a088-42ca-8dd2-fe86779b6d43.png">

Version shows "GNU coreutils 9.0, September 2021"

**Comment by fwesss** [comment]
@jonbackhaus I believe macOS always ships with the BSD version of ls. Do you use coreutils or have an alias to gnu ls?
What's the output of `which ls`?

**Comment by jonbackhaus** [comment]
Yep. :face_palm: 

```
/usr/local/opt/coreutils/libexec/gnubin/ls
/bin/ls
/usr/local/opt/coreutils/libexec/gnubin/ls
```

So that one is on me. Thanks all.

**Comment by mschrage** [comment]
It would be great if we could detect this. We could probably use the [versioning](https://fig.io/docs/handbook/versioning-completion-specs) functionality to support this.
