### ISSUE TITLE
[yarn] Recognize 'run' autocompletions

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [withfig/autocomplete#718]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [x] I would like to work on this.

### What CLI tool does this relate to?

npm, yarn

### Which statement makes the most sense?

There is a bug with this completion spec

### Issue Details

Commands passed to `yarn` and `yarn run` should detect completions from the `package.json` `"scripts"` section similarly to `npm run`. Right now they do not.

For example, these screenshots are from a [repo](https://github.com/Codecademy/gamut) with a `"test": "jest"` script where `npm run` gets autocompletions for `jest` but `yarn` and `yarn run` do not:

![Screenshot of 'npm run test' autocompleting with jest commands](https://user-images.githubusercontent.com/3335181/141159012-c2abc182-7630-41c9-9bbc-bf10dffaeb38.png)

![Screenshot of 'yarn test' autocompleting with generic commands](https://user-images.githubusercontent.com/3335181/141158958-c8f40c51-87cb-4f1c-b736-60c38d8eb680.png)

**Comment by mschrage** [comment]
Did we end up merging this in @JoshuaKGoldberg?

**Comment by JoshuaKGoldberg** [comment]
No, I went on vacation with only a Windows laptop and only got back recently 😄. I'm still pushing forward a time hold on my calendar a few days every few days to hopefully get to it soon!

**Comment by mschrage** [comment]
No worries! Just wanted to check in (since sometimes we forget to close issues when the fix is actually merged).
