### ISSUE TITLE
M1 / Arm: Bad CPU type

### ISSUE THREAD

**Issue by appinteractive** [withfig/autocomplete#724]
After installing Fig on my M1 Max machine and running Iterm2 I get following message:

```
The script at “/Users/Greg/.config/iterm2/AppSupport/Scripts/AutoLaunch/fig-iterm-integration.scpt” failed:

/Users/Greg/Library/Application Support/iTerm2/Scripts/AutoLaunch/fig-iterm-integration.scpt: execution error: sh: /Users/Greg/.fig/bin/fig: Bad CPU type in executable (126)
```

<img width="372" alt="grafik" src="https://user-images.githubusercontent.com/432828/141787549-e2ceb8e2-1b85-4d25-b3be-e76c3e99ebc8.png">

Any Suggestions? I did install Fig thorugh homebrew by the way.

**Comment by appinteractive** [comment]
I assume, that this helper is not compiled for Apple Silicon jet? I did not get any Rosetta 2 Installation dialog until now so that may be the issue!?

**Comment by appinteractive** [comment]
After installing Rosetta 2 it works fine, but you should add an error message if its not installed so it is less guesswork.

**Comment by brendanfalk** [comment]
This is fixed! Please run `fig update` and make sure you are on build 311!

Thank you so much for the detailed bug report :)
