### ISSUE TITLE
[git] git add to offer a wildcard extension

### ISSUE THREAD

**Issue by MartinPacker** [withfig/autocomplete#73]
When I update the docs for one of my GitHub projects ([md2pptx](https://github.com/MartinPacker/md2pptx) as it happens) I generate a bunch of `user_guide.*` files. It's my practice to add them with the following command:

```
git add user_guide.*

```

Today autocomplete offers each file individually. In my case I have several I want to add all at once. I like the individual file prompting but I'd like autocomplete to also offer the generic `user_guide.*`.

**Comment by mattschrage** [comment]
I like this idea a lot! To summarize: we should check to see if any of the staged files share a common prefix and then add the corresponding wildcard pattern as a suggestion?

**Comment by brendanfalk** [comment]
**Another user comment**

I was trying to git add a folder of changes eg:
* `app/web/files/change.js`
* `app/web/files/otherthing.js`

I wanted the autocomplete to stop at git add app/web/files, but there's no way to do this outside of breaking the autocomplete interface by typing a nonsensical character, or escaping the interface.

**Comment by QuiiBz** [comment]
Merged in #349, thanks to everyone!

**Comment by brendanfalk** [comment]
Going to reopen this. This PR uses two generators which is going to be really slow. We should do this with 1 generator.

**Comment by QuiiBz** [comment]
There are many other specs that use 2 generators, I don't think that really slow. We should benchmark this to see if it's really slow or not.

**Comment by QuiiBz** [comment]
Merged again in #358, using one generator (which is now really faster!)
