### ISSUE TITLE
[git] merge remote/branch auto complete does not auto complete correctly 

### ISSUE THREAD

**Issue by jpbnetley** [withfig/autocomplete#737]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [ ] I would like to work on this.

### What CLI tool does this relate to?

git

### Which statement makes the most sense?

There is a bug with this completion spec

### Issue Details

Hi.
Love your app so far.
I would just like to confirm the following regarding `git` auto complete.
My workflow usually consists of fetching the upstream, and then merging the upstream in to my local branch.
The command I use is the following.
```bash
git fetch upstream && git merge upstream/v2-develop && git push
```

the part where I merge the upstream into my develop branch, fig doesn't recognise that I am referencing a remote and then the branch.
IE `upstream/branch`
<img width="411" alt="Screen Shot 2021-11-19 at 7 59 42 AM" src="https://user-images.githubusercontent.com/25173863/142572974-26e8e2e9-5d15-49e1-8b15-3c4de7b4eeca.png">

so what fig ends up doing, is just listing that I am entering a branch name, but doesn't auto complete it.
as soon as I add the `remote/branch` part, it then suggests the branch.
Even though the branch is then already filled out.
<img width="818" alt="Screen Shot 2021-11-19 at 8 01 07 AM" src="https://user-images.githubusercontent.com/25173863/142573145-0eaf6bd2-f71d-4724-9ce8-6abbe8fbd46e.png">

Let me know if you require more information.

My system details:
**Fig version**
```
➜  ~ fig --version
fig version 1.0.52 B313

```

VS CODE version
```
**IDE: VS CODE**
Version: 1.62.2
Commit: 3a6960b964327f0e3882ce18fcebd07ed191b316
Date: 2021-11-11T20:59:05.913Z (1 wk ago)
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.1.0
```

**OS**

```
    'c.         ....
                 ,xNMM.          ----------------------------- 
               .OMMMMo           OS: macOS 12.0.1 21A559 x86_64 
               OMMM0,            Host: MacBookPro16,1 
     .;loddo:' loolloddol;.      Kernel: 21.1.0 
   cKMMMMMMMMMMNWMMMMMMMMMM0:    Uptime: 16 days, 9 hours, 5 mins 
 .KMMMMMMMMMMMMMMMMMMMMMMMWd.    Packages: 138 (brew) 
 XMMMMMMMMMMMMMMMMMMMMMMMX.      Shell: zsh 5.8 
;MMMMMMMMMMMMMMMMMMMMMMMM:       Resolution: 2048x1280@2x 
:MMMMMMMMMMMMMMMMMMMMMMMM:       DE: Aqua 
.MMMMMMMMMMMMMMMMMMMMMMMMX.      WM: Quartz Compositor 
 kMMMMMMMMMMMMMMMMMMMMMMMMWd.    WM Theme: Blue (Dark) 
 .XMMMMMMMMMMMMMMMMMMMMMMMMMMk   Terminal: HyperTerm 
  .XMMMMMMMMMMMMMMMMMMMMMMMMK.   Terminal Font: Menlo 
    kMMMMMMMMMMMMMMMMMMMMMMd     CPU: Intel i7-9750H (12) @ 2.60GHz 
     ;KMMMMMMMWXXWMMMMMMMk.      GPU: Intel UHD Graphics 630, AMD Radeon Pro 5300M 
       .cooc,.    .,coo:.        Memory: 10502MiB / 16384MiB 
```
       
       Thanks for an awesome app. 
       Keep up the good work :)

**Comment by zp4rker** [comment]
Very simple fix to this, just have to change the generator used from just local branches to both remote and local branches. The result would be like so:
<img width="1512" alt="Screen Shot 2021-11-22 at 9 02 13 am" src="https://user-images.githubusercontent.com/13144755/142780547-f9038811-65ea-4f78-bf59-4d820a09668f.png">

Submitted a PR for it: https://github.com/withfig/autocomplete/pull/743

**Comment by QuiiBz** [comment]
Thanks a lot guys!
