### ISSUE TITLE
MobiledgeX mcctl

### ISSUE THREAD

**Issue by pgale61** [withfig/autocomplete#744]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [X] I would like to work on this.

### What CLI tool does this relate to?

mcctl

### Which statement makes the most sense?

This completion spec does not exist

### Issue Details

Our CLI is in the general format `command subcommand option=value` I'm struggling to get suggestions to work for the value. Seems to work fine if it is `--option=value` but not without the dashes. Example option 
  
```
region: {
    name: "region",
    description:
      "Region name",
    requiresEquals: true,
    args: {
      name: "region",
      suggestions: [
        "EU",
        "JP",
        "US",
      ],
    }
  }
```

Also, I have a bunch of non-hyphen options. After typing command sub-command<space> I am  presented with all the options. I pick one, add the "=" and a value, hit space and there is no autocomplete list presented.  It's as if it thinks I'm done with options.

**Comment by SeparateRecords** [comment]
Related: withfig/fig#638

This can be worked around with generators, but I think it's worth waiting until this is natively supported.

<details>
<summary>However, if you do want to try now, here's a generator I haven't tested but think should work (I'll test this later!)</summary>
<br>

```typescript
function generateDashlessOptions(options: Fig.Option[]): Fig.Generator {
  // Build a map of option names to options so we can provide suggestions
  const associated = new Map<string, Fig.Option>();
  for (const option of options) {
    if (Array.isArray(option.name)) {
      option.name.forEach((name) => associated.set(name, option));
    } else {
      associated.set(option.name, option);
    }
  }

  // Now the generator:
  return {
    // Re-evaluate suggestions when `=` is pressed
    trigger: "=",
    custom: async (tokens) => {
      const finalToken = tokens[tokens.length - 1];
      const equalsIndex = finalToken.indexOf("=");

      // Still in the option name if there's no equals
      if (equalsIndex === -1) {
        return options;
      }

      // The name of the option is everything up to the =
      const name = finalToken.slice(equalsIndex);
      const option = associated.get(name);

      // There's no option for that name, nothing to suggest
      if (option === undefined) {
        return [];
      }

      const args = option.args;

      // Too much effort for this example, not supporting multiple args.
      // Although, it is possible! Happy to help with that if needed.
      if (Array.isArray(args)) {
        return [];
      }

      const suggestions = args.suggestions;

      // TS can't narrow this type to string[] or Fig.Suggestion[], has to
      // be done manually with some casting.
      if (typeof suggestions[1] === "string") {
        return (suggestions as string[]).map((name) => ({ name }));
      } else {
        return suggestions as Fig.Suggestion[];
      }
    },
  };
}
```

You'd use this on the `args` property of the subcommand, like so:

```typescript
{
  args: {
    generators: generateDashlessOptions([
      {
        name: "region",
        description: "Region name",
        requiresEquals: true,
        args: {
          name: "region",
          suggestions: [
            "EU",
            "JP",
            "US",
          ],
        },
      },
    ])
  }
}
```

</details>

**Comment by sullivan-sean** [comment]
With https://github.com/withfig/fig/issues/638 closed this should work out of the box. I've just tested your example option in a spec locally and it seems to be working as expected

**Comment by brendanfalk** [comment]
<img width="639" alt="CleanShot 2022-01-19 at 18 44 54@2x" src="https://user-images.githubusercontent.com/4949076/150262837-59d24990-7c9f-4819-a523-7234d59cd032.png">

**Comment by SeparateRecords** [comment]
Fwiw, this is fixed now!
