### ISSUE TITLE
[ssh+cd] after ssh connection, cd command will always loading

### ISSUE THREAD

**Issue by deepcoldy** [withfig/autocomplete#752]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [ ] I would like to work on this.

### What CLI tool does this relate to?

ssh

### Which statement makes the most sense?

There is a bug with this completion spec

### Issue Details

![CleanShot 2021-11-28 at 02 46 50](https://user-images.githubusercontent.com/10922642/143718634-fb6d36ca-70c5-4f11-8087-bfaaf8417380.gif)
After ssh connection, cd command will always loading.
And cd command prompt will back to normal in a few minutes.

**Comment by eranelbaz** [comment]
Happen to me consistently on zsh + iterm 

https://user-images.githubusercontent.com/29000470/143771169-f29330c9-b58b-4656-bcd5-13d7383714f4.mp4
