### ISSUE TITLE
[zsh] Incompatible with Bartender

### ISSUE THREAD

**Issue by aaronyyan** [withfig/autocomplete#761]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [X] I would like to work on this.

### What CLI tool does this relate to?

zsh

### Which statement makes the most sense?

There is a bug with this completion spec

### Issue Details
![f4xD5MIPw1nGSjt](https://i.loli.net/2021/12/01/f4xD5MIPw1nGSjt.png)

**Comment by aaronyyan** [comment]
[https://i.loli.net/2021/12/01/f4xD5MIPw1nGSjt.png](url)

**Comment by aaronyyan** [comment]
I have installed BARTENDER before this. but the message doesn't work

**Comment by mschrage** [comment]
@aaronyyan you can just type _continue_. There is no real conflict: this message is just meant to convey that running the `fig` command might not open the fig menu if you use Bartender

**Comment by aaronyyan** [comment]
> @aaronyyan you can just type _continue_. There is no real conflict: this message is just meant to convey that running the `fig` command might not open the fig menu if you use Bartender
yeah, i know, i close and uninstall the Bartender,but it still not working,`git` can be work, but `cd` not work, and there was no hint
