### ISSUE TITLE
command error

### ISSUE THREAD

**Issue by mingtianshi** [withfig/autocomplete#772]
The no-move command option can occur when you use macos, which can be fatal because you press return he executes the current command directly, resets everything, and he calls for a long time and there are errors when the command line configures the underlying command, the inability to locate the contents of the exact package, and the idea of overwriting the default retrieval command

**Comment by mschrage** [comment]
Hey @mingtianshi, I am not familiar with the `no-move` command. Can you share a screenshot of the issue or a link to the documentation?

**Comment by mingtianshi** [comment]
I'm sorry, just because of some command dependency issues

It's now settled
