### ISSUE TITLE
Add extension option to filepath template

### ISSUE THREAD

**Issue by a7med-mahmoud** [withfig/autocomplete#791]
It would be great if I can use the filepath template in the spec and choose a specific file extension to target.

**Comment by mschrage** [comment]
Hey @a7med-mahmoud,

Can you sketch out the API you imagine for this?

The current approach would be to use the `filterTermplateSuggestions` function to check the extension, but it potentially makes sense to add some syntactic sugar over this?

**Comment by a7med-mahmoud** [comment]
It would be cool if I can just do this:
```js
{
   ...
   template: {
     name: "filepath",
     options: {
        extensions: ["png", "jpg", "jpeg"]
     }
   }
}
```
Or maybe
```js
{
   ...
   template: {
     name: "filepath",
     options: {
        filter: /png|jpe?g/i
     }
   }
}
```
