### ISSUE TITLE
feature request: support parsing YAML files

### ISSUE THREAD

**Issue by miketheman** [withfig/autocomplete#799]
When building a Generator, I wanted to parse an existing YAML configuration for values to suggest to the user.

There's `JSON.parse()` today, but no `YAML.parse()` yet.

fig would need to bundle a yaml parser, like https://www.npmjs.com/package/yaml with the autocomplete-engine runtime.

**Comment by miketheman** [comment]
Wow, that seems to have worked out well! So this dep would go in the regular deps in pacakge.json?

**Comment by fedeci** [comment]
To check if this is effectively working we also need to check if a built spec importing 'yaml', is requiring it from node_modules or not. Could you give a look to the the build folder and look for require/import statements?

**Comment by miketheman** [comment]
Not sure I know what to look for - there's a lot going on in that directory.

The `pre-commit` spec I'm building that uses yaml compiles to a 225K .js file - I think largely due to importing the `git.ts` generators?

Reading the file, I don't think there's any import/require statements, I'm guessing there shouldn't be?

**Comment by fedeci** [comment]
I'll check tomorrow(Rome time) and eventually just merge the pre-commit PR if that's good, thanks for the efforts!
