### ISSUE TITLE
[git] files already git added should appear lower on autocomplete list of files

### ISSUE THREAD

**Issue by veronicanutting** [withfig/autocomplete#81]
Hey!

When i am adding files with git add, even when i already added them they still show up as top three. So i am having to use my arrow to get to new ones to add. I am on version .38

![Screen Shot 2021-03-30 at 6 17 06 PM](https://user-images.githubusercontent.com/31642442/113058595-b72fb600-9184-11eb-96c3-d21d8b873d9e.png)

**Comment by falky97** [comment]
Agree, this isn't ideal - we will take a look!!

Brendan Falk
Co-founder & CEO @ Fig
***@***.***
(857) 800-1383

**Comment by cstrnt** [comment]
Hello Veronica, 

thank you very much for reporting :) I just created a PR #208 
I'll let you know when it's merged :)

**Comment by falky97** [comment]
Merged!
