### ISSUE TITLE
[git] Add support for gitmoji inside git commit message

### ISSUE THREAD

**Issue by yaronuliel** [withfig/autocomplete#817]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [x] I would like to work on this.

### What CLI tool does this relate to?

git

### Which statement makes the most sense?

Something else

### Issue Details

When getting autocomplete for `git commit -m ` it would be great to get a list of available gitmojies
Gitmoji ( [https://gitmoji.dev/](https://gitmoji.dev/) ) is de-facto standard for  tagging commit messages visually, and is supported by all major git providers (github, bitbucket, gitlab) - having autocompletion for it is super useful, since it is hard to remember the whole list, with its nuance 

I didn't dig deep enough to check if fig already supports autocompletion for textual option values ("open answers"), but this would probably also be a good idea for possible integrations with tools like grammerly, etc...

**Comment by brendanfalk** [comment]
@yaronuliel Cleaning things up and closing this as we decided gitmoji is best served as a mixin as opposed to in the spec.
