### ISSUE TITLE
[git] `git diff` missing --stat flag

### ISSUE THREAD

**Issue by baffalop** [withfig/autocomplete#827]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [ ] I would like to work on this.

### What CLI tool does this relate to?

git

### Which statement makes the most sense?

This completion spec isn't complete

### Issue Details

This would've been a time when Fig could've shined, as I don't use this option often enough to remember it offhand.

For `git diff` there is no completion for the `--stat` flag. `git diff --stat` shows line counts for changed files. Note this can optionally take parameters, according to the help output: `--stat[=<width>[,<name-width>[,<count>]]]`.  Relatedly, there are also `--numstat` and `--shortstat` options.

In fact, it seems that the only two completions offered for `git diff` options are `--cached` and `--staged`. `git diff --help` lists many many more. I'm not sure if you prefer broad "this completion is incomplete" issues or specific issues for missing completions based on demand. I'll go with the latter, and stick to reporting just the missing `--stat` option, as that's what I was reaching for right now.

**Comment by mschrage** [comment]
@baffalop specific issues are the most helpful :)

**Comment by khaledosama999** [comment]
I will make a PR on master
