### ISSUE TITLE
Specific git shorthand commands show autocomplete for flags

### ISSUE THREAD

**Issue by mscherr-fastspot** [withfig/autocomplete#84]
OS: macOS Big Sur - 11.2.3
Terminal: iTerm2 w/ ZSH

To change branches, I usually run the command:

`git checkout -`
 
![git-checkout-shorthand](https://user-images.githubusercontent.com/61987508/113297972-4d6cf480-92c9-11eb-9398-8900ec87681b.png)

However, since the command is just the dash, Fig thinks I want to use a flag.

I would love for flags to maybe work like specific executables work (where the first option is to run the command):

![code-executable](https://user-images.githubusercontent.com/61987508/113298353-b94f5d00-92c9-11eb-9c0e-143d80e11371.png)

I know I can press `esc` to hide the autocomplete, so this is a solution; just not ideal for this command.

This might be by design, and I know this is might be an edge case, but wanted to bring it up!

Thanks for all the hard work, Fig is great.

**Comment by cstrnt** [comment]
Hey there :) Thanks for reaching out!

This is a good find. This also works with `cd`.  We can just create a subcommand for the `checkout` subcommand like this 
![Screenshot 2021-04-01 at 17 34 47](https://user-images.githubusercontent.com/20679094/113318352-ad3abe00-9310-11eb-83a1-d88f2c7fc45c.png)

**Comment by cstrnt** [comment]
I created #85 which now enables the usage of those commands 🥳

**Comment by mscherr-fastspot** [comment]
🙌 awesome, thank you.

**Comment by falky97** [comment]
Should be fixed!

If you are interested, we created it is a hidden argument suggestion for `cd` and as a normal argument suggestion for git checkout.

Brendan Falk
Co-founder & CEO @ Fig
***@***.***
(857) 800-1383
