### ISSUE TITLE
[gh] pr create option base should provide branch names

### ISSUE THREAD

**Issue by khaledosama999** [withfig/autocomplete#868]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [X] I would like to work on this.

### What CLI tool does this relate to?

gh pr create --b

### Which statement makes the most sense?

This completion spec isn't complete

### Issue Details

when typing `gh pr create --b`  the auto-complete tool should generate branch names as options for the base of my PR

**Comment by khaledosama999** [comment]
Any updates ? I can use a similar generator that is used to display git branches ?

**Comment by mschrage** [comment]
@khaledosama999 are you interested in contributing this?

**Comment by khaledosama999** [comment]
Yes, will make a PR today
