### ISSUE TITLE
React-Native Basic Commands Support

### ISSUE THREAD

**Issue by alexandruenache19** [withfig/autocomplete#87]
I would love to have the autocomplete functionality for React-Native Basic Commands like react-native run-ios, react-native start, etc

**Comment by alexnaiman** [comment]
Can I work on this?

**Comment by mattschrage** [comment]
@alexnaiman I don't think anyone else has tackled `react` CLI tooling yet. We'd love your help :)

**Comment by alexnaiman** [comment]
@mattschrage I think that this issue can be closed now
