### ISSUE TITLE
[rails] completions not showing up, only shows `new`

### ISSUE THREAD

**Issue by alDuncanson** [withfig/autocomplete#870]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [ ] I would like to work on this.

### What CLI tool does this relate to?

rails

### Which statement makes the most sense?

There is a bug with this completion spec

### Issue Details

When I type `rails` I'm only seeing one autocomplete option, `new`.

I think all of the rails cli commands should be showing up, like `generate`, `console`, `about`, etc

## fig version
![image](https://user-images.githubusercontent.com/25286675/150851283-08487387-6df2-4372-849c-90bbb2280510.png)

## macos version
![image](https://user-images.githubusercontent.com/25286675/150850980-3d0d4871-9396-43ab-881d-df3f6279668c.png)

## fig autocomplete in vscode terminal
![image](https://user-images.githubusercontent.com/25286675/150850828-db55488b-ed8d-46b8-84a7-1db2851e5c94.png)

**Comment by bolshoytoster** [comment]
@alDuncanson from `rails.ts`:
https://github.com/withfig/autocomplete/blob/a3e0f11abcbe0d18b305108168ed8a972454422d/src/rails.ts#L648-L656

If it can't find a `GemFile, it will only show `new`. I don't know why it's like that but it's probably for a good reason.

Make sure there's a `GemFile` either in your `PWD` or in one of the parents.

**Comment by alDuncanson** [comment]
Yep, I've got a `Gemfile` in the root of my current working directory

So I think something else is causing it 🤔

![image](https://user-images.githubusercontent.com/25286675/152820481-7ab1141e-4dc8-44d6-b956-2fb496d1166f.png)

**Comment by bolshoytoster** [comment]
@alDuncanson it also searches for the string `gem 'rails'` in the gemfile.

**Comment by alDuncanson** [comment]
Ahh gotcha, thanks @bolshoytoster !

**Comment by bolshoytoster** [comment]
@alDuncanson I've opened a [PR](https://github.com/withfig/autocomplete/pull/918).
