### ISSUE TITLE
`yarn workspace` does not support complete package `workspaces` specification syntax

### ISSUE THREAD

**Issue by lunelson** [withfig/autocomplete#880]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [ ] I would like to work on this.

### What CLI tool does this relate to?

yarn

### Which statement makes the most sense?

This completion spec isn't complete

### Issue Details

It looks like support for `yarn workspace` was most recently enhanced in [this PR](https://github.com/withfig/autocomplete/pull/678) however it does not yet support the complete specification. It correctly generates workspace names if the root `package.json` uses this format:

```json
{
  "workspaces": [
    "packages/*",
    "plugins/*",
    "sites/*"
  ]
}
```
...but it does not pick up workspace names if the root `package.json` is using the more complex format here:
```json
{
  "workspaces": {
    "packages": [
      "packages/*",
      "plugins/*",
      "sites/*"
    ],
    "nohoist": ["**/react-native", "**/react-native/**"]
  }
}
```

**Comment by Barzikapper** [comment]
![image](https://user-images.githubusercontent.com/98517827/151343817-3fb2d00c-2e76-437c-a59b-75376a110dac.jpeg)

**Comment by bolshoytoster** [comment]
@lunelson I've opened a pull request; I'm not entirely sure how the `packages.json` file functions (the docs weren't that helpful), so I made it just recurse the `"workspaces"` object.

If you could give me any pointers if it should be done a different way that would be helpful.

**Comment by lunelson** [comment]
@bolshoytoster honestly the whole approach that's currently in place there looks fragile to me. The best way to get information about a yarn workspace repo, rather than parsing the `package.json` and reading file directories, is to execute `yarn workspaces info`, which will send JSON to `stdout` which describes all the packages in the workspace. Just parse this and you will have all the workspace names

**Comment by bolshoytoster** [comment]
@lunelson I've implemented this in my latest commit, I did have to use `yarn workspaces --silent info` to get it to just output json but apart from that the parsing is a lot more simple than it was.

**Comment by elevatebart** [comment]
@bolshoytoster I liked your implementation plenty. 
It was not improving performance but was really fixing a hole in the tool.

I could pick up where you left off if you're OK with it.

@fedeci with your insight I think we can have something working pretty soon.

**Comment by fedeci** [comment]
Thanks @elevatebart, recover that PR then! We will add @bolshoytoster as a co-author so that he can get credit for his work!

**Comment by elevatebart** [comment]
@fedeci I finally got the minute I needed to do the work.
I hope you like it ;)
