### ISSUE TITLE
[CLI_NAME] have a support for windows 10 ?

### ISSUE THREAD

**Issue by khanhnam99** [withfig/autocomplete#885]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [ ] I would like to work on this.

### What CLI tool does this relate to?

withfig/fig

### Which statement makes the most sense?

Something else

### Issue Details

have a support for windows 10 ?

**Comment by fedeci** [comment]
See withfig/fig#35

**Comment by khanhnam99** [comment]
thanks
