### ISSUE TITLE
[gpg] add completions

### ISSUE THREAD

**Issue by uzza1hossain** [withfig/autocomplete#890]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [ ] I would like to work on this.

### What CLI tool does this relate to?

gpg

### Which statement makes the most sense?

This completion spec does not exist

### Issue Details

See [gpg man page](https://www.gnupg.org/documentation/manpage.html)

**Comment by bolshoytoster** [comment]
I can probably do this, it doesn't look too complicated.

Thank you for linking the man page btw.

**Comment by mschrage** [comment]
That would be amazing @bolshoytoster! Thank you so much 🙏

**Comment by bolshoytoster** [comment]
I'm about halfway through now, would it be worth adding autocomplete for user IDs? If so, how would I do that since it looks like `gpg --list-keys` differs between versions.

**Comment by mschrage** [comment]
See [this documentation](https://fig.io/docs/handbook/versioning-completion-specs) on how you can write specs that target multiple versions of the CLI tool. If it seems to tricky to write a generator, just do the skeleton for the time being.

**Comment by uzza1hossain** [comment]
@bolshoytoster Thanks for working on this issue.

**Comment by bolshoytoster** [comment]
I've finished the skeleton (+ a generator to detect supported algorithms from `gpg --version`). I'm not sure if I can open a PR since I already have one open for an unrelated issue, you can clone my [gpg](https://github.com/bolshoytoster/autocomplete/tree/gpg) branch for now.

**Comment by uzza1hossain** [comment]
@mschrage Can you please check gpg pull request and merge so that we can use it from main Branch

**Comment by mschrage** [comment]
I don't see a PR for `gpg` @uzza1hossain? 

Let's merge in your outstanding PR @bolshoytoster!

**Comment by bolshoytoster** [comment]
@mschrage I've opened a PR: #910

**Comment by uzza1hossain** [comment]
Thanks a lot, @bolshoytoster for working on this issue.
@mschrage thanks for merging.
I am closing this issue.
