### ISSUE TITLE
[gh] `pr edit` spec missing

### ISSUE THREAD

**Issue by thiskevinwang** [withfig/autocomplete#900]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [ ] I would like to work on this.

### What CLI tool does this relate to?

gh

### Which statement makes the most sense?

This completion spec does not exist

### Issue Details

`gh pr edit` is missing completion

Fig `Version 1.0.55 (B365)`

**Comment by ShawnCockburn** [comment]
@thiskevinwang this will be fixed when #905 is merged

**Comment by ShawnCockburn** [comment]
@thiskevinwang Done
