### ISSUE TITLE
[nerdctl] completion required

### ISSUE THREAD

**Issue by kxxoling** [withfig/autocomplete#908]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [X] I would like to work on this.

### What CLI tool does this relate to?

nerdctl

### Which statement makes the most sense?

This completion spec does not exist

### Issue Details

[`nerdctl`](https://github.com/containerd/nerdctl) is a `docker` replacement, which supports almost the same command line interface. I find `src/docker.ts` and `src/docker` in the source folder. How should I create an similar completion for `nerdctl`? I don't think simple copy-paste is a good idea.

**Comment by kxxoling** [comment]
I think it would be good to have something like inheritation or polymorphism.

**Comment by fedeci** [comment]
Specs are designed to be as simple as possible and (almost) just rely on JS objects. What I suggest you to do is to refactor the docker spec in a way that you can easily import parts of that spec in the nerdctl one.

**Comment by bolshoytoster** [comment]
@kxxoling I'm not that well-versed in java/typescript but you might be able to do something like:
```ts
dockerSpec = require('docker.ts').completionSpec
```
Then in your spec you could add `...dockerSpec` to add the specs.

Again, I'm not too sure, but you could try something like that.

**Comment by mschrage** [comment]
@kxxoling if `nerdctl` has an identical interface to `docker`, you can do something like this: https://github.com/withfig/autocomplete/blob/master/src/kubecolor.ts

**Comment by kxxoling** [comment]
The most confusing part is there's hard coded "docker" in descriptions and comments. Is that OK to have it in `nerdctl.ts` just like `kubecolor`?

**Comment by mschrage** [comment]
Oh interesting. You could probably do something fancy using `generateSpec` to recursively iterate over the `docker` spec and replace occurrences of `docker` with `nerdctl`!

**Comment by fedeci** [comment]
I wouldn't use generateSpec since that's heavier for our runtime, but I would rather use a simple function returning the static commands with string interpolation:
```js
function getStaticOptions(cli = "docker") {
return [{
  name: "--foo"
  description: `Some ${cli} description`
}]
}
```

**Comment by mschrage** [comment]
This is tricky @fedeci since the docker spec is autogenerated using the cobra integration. 
 I do like this this idea and agree that using generateSpec at runtime is less than ideal.

I wonder if we can do something like `generateSpec` at compile time? Could be called `generateStaticSpec`?

**Comment by fedeci** [comment]
`generateStaticSpec` makes sense. I can do a couple tests with TS AST.

**Comment by fedeci** [comment]
Thanks! I'm doing the persistent expanded description right now, I'll check that out tomorrow.

**Comment by fedeci** [comment]
> `generateStaticSpec` makes sense. I can do a couple tests with TS AST.

@mschrage I'll summarize my considerations while I was writing down an RFC for this feature:
The possible interface we want is `generateStaticSpec: () => Omit<Fig.Spec, 'generateStaticSpec'>`.
`Fig.Spec` however is a deeply nested object composed of functions, strings, arrays...etc. (basically all the JS types).
Once we run `eval(generateStaticSpec)` we get that complex object in memory as a result, however we cannot bring all the properties back to stringified code. For example functions cannot be reparsed to string.

**Comment by fedeci** [comment]
I am closing this one since meta-programming seems a too complex topic for specs, we can talk more about this in the future :)
