### ISSUE TITLE
Add ability to specify custom timeout when running a script

### ISSUE THREAD

**Issue by mschrage** [withfig/autocomplete#96]
Currently, this defaults to 5 seconds. Should we add a new property to the `Generator` that allows this to be customized?

See #91 for an example of when this is necessary. (tl;dr long running commands like `adb` and `xcodebuild` frequently timeout)

**Comment by alexnaiman** [comment]
I think that an additional property, as mentioned, would be really helpful.
Some commands like those from `adb` take more time to execute just the first time. The subsequent runs after should take less time to execute.

**Comment by falky97** [comment]
Will actually be a little hard to do. We set time outs for the entire autocomplete function, not just the generators... To do this, we would have to remove timeouts for the whole function... This is doable, will just need to think it through so we can support this but make sure Fig still handles non-generator errors.

Also, we need to add a loading icon when a generator is running...

**Comment by mattschrage** [comment]
Just added #104

**Comment by mschrage** [comment]
@fedeci this is worth implementing, if you have some spare time - I don’t think it’ll be too tricky anymore.
