### ISSUE TITLE
[tar] missing options

### ISSUE THREAD

**Issue by SeparateRecords** [withfig/autocomplete#962]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [ ] I would like to work on this.

### What CLI tool does this relate to?

tar

### Which statement makes the most sense?

This completion spec isn't complete

### Issue Details

There's a lot missing from this spec, check out `man tar`

**Comment by bolshoytoster** [comment]
@SeparateRecords I can work on this.

I don't think autocomplete supports the 'clusters' that tar has (e.g. tar __cfv__ a.tar /etc) but I can add them as seperate options.

**Comment by SeparateRecords** [comment]
@bolshoytoster that would be amazing!

I think you could use an argument with a generator for that actually. Would take some experimentation to get it to feel right though.

**Comment by bolshoytoster** [comment]
@SeparateRecords I'm not sure if that would look that good - there are loads of arguments for tar (There are 575 lines in my `tar.ts` currently).

I could make it just support common clusters (i.e. xzvf).

**Comment by SeparateRecords** [comment]
Yeah with that many options it probably wouldn't look good... I trust your judgement on this! `chmod` is similar, it only suggests the most common permissions.

<img width="400" alt="chmod completions" src="https://user-images.githubusercontent.com/52195359/155250682-eeb25a99-11c9-420e-b233-af79c429a5f5.png">

**Comment by bolshoytoster** [comment]
@SeparateRecords I've opened a [PR](https://github.com/withfig/autocomplete/pull/970).
