### ISSUE TITLE
[npm] rank popular packages higher

### ISSUE THREAD

**Issue by SeparateRecords** [withfig/autocomplete#974]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [ ] I would like to work on this.

### What CLI tool does this relate to?

npm

### Which statement makes the most sense?

Something else

### Issue Details

Currently if I write `npm i vi` I get this:
<img width="438" alt="CleanShot 2022-02-25 at 13 02 49@2x" src="https://user-images.githubusercontent.com/52195359/155802633-c3e809e8-b43a-4875-bb0b-4845f5ae05c1.png">

I think most people would expect to see `vite` near the top given how popular it is.

**Comment by bolshoytoster** [comment]
@SeparateRecords it looks like even if I set the `popularity-weight` to 96 (default 1.95) vite isn't in the top 20 for this.
