### ISSUE TITLE
[npm]: Missing options for several npm commands

### ISSUE THREAD

**Issue by harimm** [withfig/autocomplete#983]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [X] I would like to work on this.

### What CLI tool does this relate to?

npm

### Which statement makes the most sense?

This completion spec isn't complete

### Issue Details

The completion spec does not include certain options for some commands - 

for example: `--registry` for `ping`, `star`, `unstar` etc.

Also certain aliases are incorrectly shown as independent commands. 

For example `v` should be an alias for `view` but is shown incorrectly as a separate command, and `up` should be an alias for `update`, but shown incorrectly as a separate command

EDIT: updated for clarity

**Comment by harimm** [comment]
Partially fixed with https://github.com/withfig/autocomplete/pull/1001. There are still more improvements needed

**Comment by harimm** [comment]
Another set of changes merged with https://github.com/withfig/autocomplete/pull/1019

**Comment by brendanfalk** [comment]
These are all included so closing for now
