### ISSUE TITLE
[git] git reve-parse command

### ISSUE THREAD

**Issue by vashian** [withfig/autocomplete#987]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [ ] I would like to work on this.

### What CLI tool does this relate to?

git

### Which statement makes the most sense?

There is a bug with this completion spec

### Issue Details

Hi.
I was trying to use `git rev-parse HEAD` 
But fig auto-completion couldn't help me out

**Comment by vashian** [comment]
`git tag --points-at`
again no auto-completion for this command

**Comment by mschrage** [comment]
@vashian would you be interested in adding these missing options and arguments to the git completion spec?

**Comment by vashian** [comment]
@mschrage 
Of course, I'm interested in
for getting started I just try to add a new flag for `git tag`
I'll add a new command for `git` in my free time too
