### ISSUE TITLE
`cp` (and potentially other commands like `mv`) should accept both files and folders for destination argument

### ISSUE THREAD

**Issue by mattschrage** [withfig/autocomplete#99]
### Completion Spec
`cp`

### Description
I want to copy a file to a folder (eg. `cp ~/path/to/file ~/path/to/another/folder`) which is valid - however the second argument of the `cp` completion spec seems to only accept a filepath. The red arrow that allows me to run the command immediately does not appear.

### System Information

*Fig Version:*  1.0.39

*OS:* 10.15.7 (19H2)

*Device:* MacBook Pro

### Potential Solution

Add folder to `templates` in completion spec.

**Comment by falky97** [comment]
https://github.com/withfig/autocomplete/commit/dc7a3907e81b342b9f2379083a67443fe003fc41 this merge fixed cp. Doing another now for `mv`. Have to add `template: ["filepaths", "folders"]`
