### ISSUE TITLE
npm bugs does not open this issues page

### ISSUE THREAD

**Issue by harimm** [withfig/autocomplete#993]
Running `npm bugs` from the root of the repository should open this issues page. - https://github.com/withfig/autocomplete/issues/

Or alternately running `npm bugs @withfig/autocomplete` from anywhere should open this issues page

Indicates that the bug reporting page is missing from the package information

**Comment by mschrage** [comment]
@harimm would you be opening to contributing a fix for this?

**Comment by harimm** [comment]
Yes. let me take a crack at that @mschrage

**Comment by harimm** [comment]
I have added a PR for this and verified that running `npm bugs` from the repo does in fact point to this issues page - `https://github.com/withfig/autocomplete/issues`. 

The `npm bugs @withfig/autocomplete` still points to the package url at `https://www.npmjs.com/package/@withfig/autocomplete`

I think the newer builds of @withfig\autocomplete having this metadata change should point to the issues url

**Comment by mschrage** [comment]
Thank you so much for contributing this fix!

**Comment by harimm** [comment]
The pleasure is mine! @mschrage

I just ran `npm bugs @withfig/autocomplete` and it correctly points to `https://github.com/withfig/autocomplete/issues`
