### ISSUE TITLE
[git] git apply is not suggested

### ISSUE THREAD

**Issue by harimm** [withfig/autocomplete#998]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [X] I would like to work on this.

### What CLI tool does this relate to?

git

### Which statement makes the most sense?

This completion spec isn't complete

### Issue Details

For the `git` command, `apply` subcommand is missing

**Comment by mschrage** [comment]
That's for working on this @harimm - the `git` spec is full of surprising gaps like this since it wasn't autogenerated.
